### ISSUE TITLE
mcs-finding should be more robust

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/rules_dotnet#1]
See http://ci.bazel.io/job/rules_dotnet/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/3/console:

```
____[7 / 11] Compiling examples/example_transitive_lib:TransitiveClass
ERROR: /home/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/examples/example_transitive_lib/BUILD:3:1: error executing shell command: '/usr/local/bin/mcs -out:bazel-out/local_linux-fastbuild/bin/examples/example_transitive_lib/TransitiveClass.dll -target:library -fullpaths -warn:4 -nologo -doc:bazel-out/local_linux-fastbuild/bin/e...' failed: namespace-sandbox failed: error executing command 
  (cd /home/ci/.cache/bazel/_bazel_ci/1471c2a9e7dce6d4e1d950b43de46d01/linux-x86_64 && \
  exec env - \
  /home/ci/.cache/bazel/_bazel_ci/1471c2a9e7dce6d4e1d950b43de46d01/linux-x86_64/_bin/namespace-sandbox @/home/ci/.cache/bazel/_bazel_ci/1471c2a9e7dce6d4e1d950b43de46d01/linux-x86_64/bazel-sandbox/e5591ace-6edb-42f2-b6ab-9581eb783b26-0.params -- /bin/bash -c '/usr/local/bin/mcs -out:bazel-out/local_linux-fastbuild/bin/examples/example_transitive_lib/TransitiveClass.dll -target:library -fullpaths -warn:4 -nologo -doc:bazel-out/local_linux-fastbuild/bin/examples/example_transitive_lib/TransitiveClass.xml -debug examples/example_transitive_lib/Properties/AssemblyInfo.cs examples/example_transitive_lib/TransitiveClass.cs' '' -out:bazel-out/local_linux-fastbuild/bin/examples/example_transitive_lib/TransitiveClass.dll -target:library -fullpaths -warn:4 -nologo -doc:bazel-out/local_linux-fastbuild/bin/examples/example_transitive_lib/TransitiveClass.xml -debug).
: /usr/local/bin/mcs: No such file or directory
```

Right now /usr/local/bin/mcs is hardcoded and I'm not sure it's included in the sandbox.

**Comment by damienmg** [comment]
What is the status of thhis?

**Comment by davidzchen** [comment]
I opened a PR for this (#4). Can you take a look?

**Comment by damienmg** [comment]
Oops sorry I have missed that mail. It's kind of hard to keep track of things on github...

**Comment by damienmg** [comment]
Error:

Cannot find %s. Either correct your path or set the %s environment variable. and referenced by '//external:csc'.


Actually, can't we just the compilers from the net?

**Comment by zaphar** [comment]
The correct long term fix is to get the mono distribution as an external repository. But this is non-trivial since they don't ship them as tarballs or zip files for anything. I've got it on my todo list to tackle at some point but haven't gotten around to it yet.

**Comment by davidzchen** [comment]
@zaphar Agreed. Thanks for looking into it! That would be great to have.

**Comment by damienmg** [comment]
Yes. In the time between testing the dotnet rules fails even when installed the dotnet package on ubuntu...

**Comment by zaphar** [comment]
For future reference:

This is how the mono project gets stuff from binary package releases for mac unpacked on other platforms:

https://github.com/mono/release/blob/master/defs/managed-components#L52

We may be able to use a similar mechanism ourselves.

**Comment by kchodorow** [comment]
https://github.com/bazelbuild/rules_dotnet/pull/7 should fix some of the issues mentioned.
