### ISSUE TITLE
error to download .Net Core sdk version v2.1.502

### ISSUE THREAD

**Issue by nmalsang** [bazelbuild/rules_dotnet#107]
An error happens during the download of the .net core sdk version v2.1.502. It looks like this version is not available. I fix it by using the version v2.1.503. 
I can suggest my fix .

**Comment by tomaszstrejczek** [comment]
The PR would be highly appreciated.

**Comment by nmalsang** [comment]
The PR is coming soon

**Comment by nmalsang** [comment]
I prepare a first fix for the rules for .Net Core and add a unit test on my fork. 
But I have as dependency for my unit test : "@io_bazel_rules_dotnet//dotnet/stdlib.core:mscorlib.dll",
as you can see here : 
  core_binary(
    name = "custom_bin",
    srcs = [
        "main.cs",
    ],
    out = "alt_bin.exe",
    deps = [
        "@io_bazel_rules_dotnet//dotnet/stdlib.core:mscorlib.dll",
    ],

I would like remove this here because mscorlib.dll and its dependencies are standard default libraries that we always need to build a c# file.  The dotnet csc.dll command line needs to reference by default all the dependencies of mscorlib.dll mentioned in the file //dotnet/stdlib.core/macro.bzl. I would like modify the file //dotnet/private/actions/assembly_core.bzl at line 54 where we write the command line to compile to add a loop on the dependencies of mscorlib.dll and write /reference ***.dll in the command line. If I well understood I need to create a depset from the string "@io_bazel_rules_dotnet//dotnet/stdlib.core:mscorlib.dll" but I don't see how to do that. 
Does anyone could help me to do that please? or explain me how to do that?
Thanks in advance

**Comment by nmalsang** [comment]
the code I try to do : 
    




in assembly_core.bzl line 54 : 
std_deps = ???? the dependencies of mscorlib.dll ???
    transitive_std_deps = depset(direct = std_deps, transitive = [d[DotnetLibrary].transitive for d in std_deps])
    args.add_all(transitive_std_deps, format_each = "/reference:%s", map_each = _map_dep)

Any suggestion is welcome.
Thanks
