### ISSUE TITLE
error in WORKSPACE for xunit 

### ISSUE THREAD

**Issue by nmalsang** [bazelbuild/rules_dotnet#108]
In the WORKSPACE 
I had to fix two issue about xunit
- strip_prefix miising for abstractions.xunit-2.0.1 
- @io_bazel_rules_dotnet is missing in the path of the build_file for xunit-2.4.1
I can provide the fix

**Comment by tomaszstrejczek** [comment]
Please do. Appreciated.

**Comment by nmalsang** [comment]
The PR is coming soon

**Comment by VVKot** [comment]
@nmalsang Have you submitted the PR?

**Comment by nmalsang** [comment]
@VVKot I will submit a first PR. xunit would need a toolchain
to select the framework version but I have not the time to do it now.

**Comment by nmalsang** [comment]
Merged #127 into master.
