### ISSUE TITLE
Unrecognized file mode for nuget library (Remotion.Linq)

### ISSUE THREAD

**Issue by Dopingus** [bazelbuild/rules_dotnet#116]
Hello,

I'm currently trying to set up a Bazel build for a .net core (2.2) webapp project (references Microsoft.AspNetCore.App).
I figured out how to configure/declare all dependencies, however when I try to add Remotion.Linq (2.2.0) Bazel quits with an IOException.

The lib itself seems to download just fine, but during extraction an exception is thrown.
My setup is macOS 10.14.3, rules_dotnet master branch, and Bazel 0.23.1.

```
INFO: SHA256 (https://www.nuget.org/api/v2/package/Remotion.Linq/2.2.0) = ae93e9db1c878f626c4f2ea4dc5021963be5f393cd6b747d8eb572dd41b486f8
java.io.IOException: Error extracting /private/var/tmp/_bazel_d072124/0817235a9f3a8096f1bb2947ce5da081/external/remotion-linq/2.2.0.zip to /private/var/tmp/_bazel_d072124/0817235a9f3a8096f1bb2947ce5da081/external/remotion-linq: Unrecognized file mode for [Content_Types].xml: 0x80 and referenced by '//modules/csharp-endpoint/CSharp.Project:csharp-endpoint'
```

Thanks & Regards

**Comment by Dopingus** [comment]
Just tested this in a Bazel container and getting the same exception

**Comment by tomaszstrejczek** [comment]
The problem is specific to bazel implementation of zip extract function. I've reported the issue to bazel project: https://github.com/bazelbuild/bazel/issues/9236.
