### ISSUE TITLE
Generate Visual Studio csproj files for csharp code.

### ISSUE THREAD

**Issue by zaphar** [bazelbuild/rules_dotnet#12]
It would be nice if a csharp_binary or csharp_library target could be used to generate csprob files for the IDE users out there. It would go a long way to making this usable by MonoDevelop users.

**Comment by davidzchen** [comment]
+cc @dslomov 

This would be an excellent use case for Skylark Aspects.

**Comment by lupin-de-mid** [comment]
May be anybody has some hints how to generate this project file from bazel rules

**Comment by lupin-de-mid** [comment]
I'm ready to generate this from csharp, but may be there are more bazelish way

**Comment by purkhusid** [comment]
Duplicate of #258. Closing
