### ISSUE TITLE
Test rules do not execute when using --incompatible_windows_native_test_wrapper

### ISSUE THREAD

**Issue by jimevans** [bazelbuild/rules_dotnet#128]
Bazel 0.25 implements the ability to run `bazel test` rules without using Bash by including a flag, `--incompatible_windows_native_test_wrapper`. According to [this Bazel issue](https://github.com/bazelbuild/bazel/issues/6622), this flag will become the default behavior in 0.27. When attempting to run an NUnit test using `bazel test` and the `--incompatible_windows_native_test_wrapper` flag in Bazel 0.25 or 0.26, the target fails with `%1 is not a valid Win32 application.`

**Comment by laurentlb** [comment]
The flag will not be flipped in Bazel 0.27. See the labels on https://github.com/bazelbuild/bazel/issues/6622 (or the latest messages). So you have a few months to do the migration.

**Comment by jimevans** [comment]
@laurentlb Making the flag not flip in 0.27 is actually worse for my case than better. Something in the way the .NET rules sets up their test execution environment using bash prevents one of the executables my test relies on from running properly (somehow blocking the [Windows `IELaunchURL` API](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767962(v=vs.85)) from working properly, probably because of an environment config mismatch). I don't know if it's Bazel or the .NET rules, but I do know it's something specific to this particular bash environment, because I can use a manually started (msys2) bash shell, and it works properly.

My attempt to migrate the created shell script from bash to Windows `cmd.exe` in a PR has proven pointless, because I can't seem to get the ["manifest prep" step](https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/private/rules/test.bzl#L100) to work in the non-bash environment. I was rather hoping that the impending removal of the flag would act as a forcing function to get this issue resolved so I can use Bazel to build and test my .NET-based project. Forgive me if I'd rather not wait "a few months" to have this working.

**Comment by laurentlb** [comment]
@laszlocsomor might be able to help (but he's on vacation this month) or @meteorcloudy maybe.

**Comment by tomaszstrejczek** [comment]
@jimevans I'm working on native (C-based) launchers instead of bash scripts. It will take couple more days to get it done.

**Comment by jimevans** [comment]
@tomaszstrejczek That's supremely good news, especially if it's only a matter of days. If there's anything I can do to help that process along, do let me know.
