### ISSUE TITLE
Fix ci.bazel.io 

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_dotnet#13]
dotnet build have been red from the begining because there is no mono on the machine. Even installing mono did not fix the build.

Can someone have a real look at this?

/cc @kchodorow @davidzchen @zaphar

**Comment by zaphar** [comment]
I would but I don't think I have the necessary access.

**Comment by damienmg** [comment]
The view should be public:
http://ci.bazel.io/job/rules_dotnet/

you can click around. As a googler you also have the possibility to run a build though it won't help you because you have to merge the change before.

I don't think installing more stuff on the slaves will helps but for reference the source code is at http://bazel.googlesource.com/continuous-integration

**Comment by zaphar** [comment]
I'm actually not a Googler currently :-). I used to be.

**Comment by damienmg** [comment]
ping?

**Comment by zaphar** [comment]
So I looked at the build that isn't failing due to missing mono. It seems
to be failing because it can't find the minor build file which I think we
have already fixed. Are we sure it's using the latest version of bazel?

**Comment by zaphar** [comment]
That was nunit not minor build file. Stupid phone

**Comment by damienmg** [comment]
This is testing against bazel 0.2.1 (now will be testing against bazel 0.2.2) and HEAD

**Comment by damienmg** [comment]
0.2.1 is broken because of the Label syntax which is not yet available (should be fixed on next push).

http://ci.bazel.io/job/rules_dotnet/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/53/console is the actual problem:
```
+ /home/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/bazel-install/binary/bazel --bazelrc=/home/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/bazel-install/bazel.bazelrc build //...
____Loading...
ERROR: /home/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/examples/example_lib/BUILD:3:1: every rule of type csharp_library implicitly depends upon the target '@local_config_csharp//:mono', but this target could not be found because of: no such package '@local_config_csharp//': Traceback (most recent call last):
	File "/home/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/dotnet/csharp.bzl", line 267
		_find_and_symlink(repository_ctx, "mono", "MONO")
	File "/home/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/dotnet/csharp.bzl", line 262, in _find_and_symlink
		fail("Cannot find %s. Either correct ...)
Cannot find mono. Either correct your path or set the MONO environment variable..
ERROR: /home/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/examples/example_binary/BUILD:3:1: every rule of type csharp_binary implicitly depends upon the target '@local_config_csharp//:mono', but this target could not be found because of: no such package '@local_config_csharp//': Traceback (most recent call last):
	File "/home/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/dotnet/csharp.bzl", line 267
		_find_and_symlink(repository_ctx, "mono", "MONO")
	File "/home/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/dotnet/csharp.bzl", line 262, in _find_and_symlink
		fail("Cannot find %s. Either correct ...)
Cannot find mono. Either correct your path or set the MONO environment variable..
ERROR: Loading failed; build aborted.
____Elapsed time: 1.115s
```

**Comment by damienmg** [comment]
(note that mono is not installed on those machine, I did a test where I installed mono on one of the slave but it did not solve the problem).

If mono is an absolute dependency, maybe we should vendor it on GCS

**Comment by zaphar** [comment]
Until I work out the mono package as external repository it is a hard
dependency.

**Comment by damienmg** [comment]
Sorry forgot to answer, we are going to deactivate ci coverage for it, please ping back when you figure out a good way to do it.

**Comment by damienmg** [comment]
I reactivated the job only for darwin but it still fails:

```
 /Users/ci/.bazel/HEAD/bin/bazel --bazelrc=/Users/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/bazel.bazelrc build //...
ERROR: /Users/ci/workspace/rules_dotnet/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/WORKSPACE:3:6: no such variable: csharp_configure.
ERROR: Error evaluating WORKSPACE file.
ERROR: package contains errors: dotnet.
ERROR: error loading package 'external': Package 'external' contains errors.
```

**Comment by damienmg** [comment]
Now it is green. So only linux is left :+1

**Comment by zaphar** [comment]
Sorry about that I forgot to modify the workspace file there.

**Comment by damienmg** [comment]
No problem, it was easy to fix :)

**Comment by damienmg** [comment]
Closing this one because there is already #14
