### ISSUE TITLE
Rules now ignore 'out' argument for name of output artifact

### ISSUE THREAD

**Issue by jimevans** [bazelbuild/rules_dotnet#130]
Introduced in 6f44752, the rules now expect that the name of the created artifact by a rule indicates its file name in the file system, completely ignoring the `out` attribute of the rule. This also breaks existing build files and downstream rules that may rely on the output of the .NET build rules as their inputs (for example, merging component and dependent assemblies to a single assembly using `ILMerge` or similar).

**Comment by tomaszstrejczek** [comment]
My bad. I will fix it soon.

**Comment by jimevans** [comment]
I may have a PR in a few minutes, if you like.

**Comment by tomaszstrejczek** [comment]
It's more than welcome
