### ISSUE TITLE
Where can I add compile options in a dotnet_binary rule. Using mcs.

### ISSUE THREAD

**Issue by scp096** [bazelbuild/rules_dotnet#135]

**Comment by tomaszstrejczek** [comment]
Which options would you like to use? I'd rather prefer adding appropriate rule attribute to provide necessary feature. For example, a key file for signing is handled via the keyfile attribute.

**Comment by scp096** [comment]
@tomaszstrejczek , thanks for the reply.  A debug compile option is what I need.

**Comment by tomaszstrejczek** [comment]
@scp096 you can set compilation mode to debug by executing bazel build with -c dbg command line option:
bazel build -c dbg //...

**Comment by scp096** [comment]
@tomaszstrejczek It doesn't work for me, didn't generate any mdb file（should be generated by mcs complie with debug option).

**Comment by tomaszstrejczek** [comment]
Debug build was not supported for mono. I've just added the support with #139. It should work now.

**Comment by scp096** [comment]
@tomaszstrejczek Thanks a lot.
