### ISSUE TITLE
Pull in mono as an external workspace.

### ISSUE THREAD

**Issue by zaphar** [bazelbuild/rules_dotnet#14]
This is going to require platform specific repositories probably.

On OS-X we can probably reuse some of this code: https://github.com/mono/release/blob/master/defs/managed-components#L52

For Linux we can probably unpack one of the distro packages.

For MS I'm not sure what we should do but that can probably wait till bazel windows support is stabilized.

**Comment by tomaszstrejczek** [comment]
I couldn't find any downloadable working in-place (without installing) mono installation for Windows or Linux. 
A similar problem exists for .NET.

**Comment by purkhusid** [comment]
Cleaning up. Going to close this for now since Mono is out of scope at the moment.
