### ISSUE TITLE
.NET rules produce unusable .NET Standard assemblies

### ISSUE THREAD

**Issue by jimevans** [bazelbuild/rules_dotnet#142]
When building .NET Standard 2.0 assemblies with the current .NET rules for Bazel, the resulting assembly is not usable as a reference in .NET Core projects. The symptom of the issue is when using the resulting assembly, you receive compilation errors of the form:

    error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.

To reproduce, clone the example project located at https://github.com/jimevans/BazelDotNetStandardExample

Execute the following command:

    bazel build //BazelDotNetStandardExample/ClassLibrary1:example

If you use the resulting assembly (which can be found at `bazel-out\x64_windows-fastbuild\bin\BazelDotNetStandardExample\ClassLibrary1\ClassLibrary1.dll`) as a reference in a .NET Core project, you will be unable to create an instance of type `Class1` from the library.

Examining the resulting assembly using ildasm, the references created by the rules are not the same as the ones created by Visual Studio for the same project. To wit, the references in the manifest for the assembly generated by the Bazel rules are:

> // Metadata version: v4.0.30319
.assembly extern System.Private.CoreLib
{
  .publickeytoken = (7C EC 85 D7 BE A7 79 8E )                         // |.....y.
  .ver 4:0:0:0
}
.assembly extern System.Private.Uri
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:0:5:0
}

By contrast, the references in the manifest for the assembly generated by Visual Studio for the same project are:

>// Metadata version: v4.0.30319
.assembly extern netstandard
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 2:0:0:0
}

**Comment by jimevans** [comment]
Ideally, I believe a way forward would be to use the binaries contained in the [NETStandard.Library NuGet package](https://www.nuget.org/packages/NETStandard.Library/2.0.3) as the reference assemblies that make up the stdlib for the SDK (instead of the ones that ship with the .NET Core SDK). I'm not entirely sure how to manage that, whether a new type of library generation rule (that would live alongside `dotnet_library`, `core_library`, and `net_library`) is needed, or if things can be shoehorned into working directly with one of them.

**Comment by tomaszstrejczek** [comment]
.NET Standard libraries should now work if built using .NET Core toolchain. See https://github.com/bazelbuild/rules_dotnet/tree/master/tests/examples/netstandard
