### ISSUE TITLE
Can't use rules_dotnet on machine without mono installed

### ISSUE THREAD

**Issue by noahl** [bazelbuild/rules_dotnet#145]
I'm working on a Windows machine with .NET Framework and .NET Core installed, trying to build a .NET Framework project.

I first tried setting up my WORKSPACE like this:
```dotnet_register_toolchains()
dotnet_repositories()
# For .NET Framework:
net_register_sdk("net471", name = "net_sdk")
```

I got several errors like this:
```ERROR: C:/users/nolavine/_bazel_nolavine/p6itprpv/external/io_bazel_rules_dotnet/BUILD:6:1: every rule of type dotnet_context_data implicitly depends upon the target '@dotnet_sdk//:mcs_bin', but this target could not be found because of: no such package '@dotnet_sdk//': The repository '@dotnet_sdk' could not be resolved```

Then I tried adding dotnet_register_sdk() and core_register_sdk() calls to my WORKSPACE. I was able to get a different error:
```INFO: Call stack for the definition of repository 'dotnet_sdk' which is a dotnet_host_sdk (rule definition at C:/users/nolavine/_bazel_nolavine/p6itprpv/external/io_bazel_rules_dotnet/dotnet/private/sdk.bzl:66:19):
 - C:/users/nolavine/_bazel_nolavine/p6itprpv/external/io_bazel_rules_dotnet/dotnet/toolchain/toolchains.bzl:275:5
 - C:/vso/src/WORKSPACE:20:1
ERROR: An error occurred during the fetch of repository 'dotnet_sdk':
   Traceback (most recent call last):
        File "C:/users/nolavine/_bazel_nolavine/p6itprpv/external/io_bazel_rules_dotnet/dotnet/private/sdk.bzl", line 64
                _dotnet_host_sdk_impl_windows(ctx)
        File "C:/users/nolavine/_bazel_nolavine/p6itprpv/external/io_bazel_rules_dotnet/dotnet/private/sdk.bzl", line 10, in _dotnet_host_sdk_impl_windows
                _detect_host_sdk(ctx)
        File "C:/users/nolavine/_bazel_nolavine/p6itprpv/external/io_bazel_rules_dotnet/dotnet/private/sdk.bzl", line 96, in _detect_host_sdk
                fail("Failed to find mcs")
Failed to find mcs
```

It looks like I need to have mono installed on my machine in order to proceed. Is there a way around this? I'd be happy to make the changes myself if necessary, but I would appreciate pointers to the right places from someone familiar with the codebase. Thanks!

**Comment by tomaszstrejczek** [comment]
Could you post the full output of your bazel build command?
Which version of .NET Framework do you have installed?
Please see an example which should work without mono installed:
[a.zip](https://github.com/bazelbuild/rules_dotnet/files/3547464/a.zip)

**Comment by thesayyn** [comment]
I'm having this issue as well.

**Comment by tomaszstrejczek** [comment]
@thesayyn Could you try the latest version of rules_dotnet (0.0.4) with bazel 1.1.0?

**Comment by thfabian** [comment]
Looks like this has not been fixed. I'm still getting this issue
```
DEBUG: Rule 'io_bazel_rules_dotnet' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "a8f5820a326180e7c9ec9f333bb9081efc843033", shallow_since = "1578483019 +0100" and dropping ["branch"]
DEBUG: Call stack for the definition of repository 'io_bazel_rules_dotnet' which is a git_repository (rule definition at C:/users/X/_bazel_X/fiijdbw7/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - C:/a/WORKSPACE:3:1
ERROR: C:/a/BUILD:3:1: in dotnet_binary rule //:a.exe:
Traceback (most recent call last):
        File "C:/a/BUILD", line 3
                dotnet_binary(name = 'a.exe')
        File "C:/users/X/_bazel_X/fiijdbw7/external/io_bazel_rules_dotnet/dotnet/private/rules/binary.bzl", line 18, in _binary_impl
                dotnet_context(ctx)
        File "C:/users/X/_bazel_X/fiijdbw7/external/io_bazel_rules_dotnet/dotnet/private/context.bzl", line 56, in dotnet_context
                toolchain.get_dotnet_runner(<2 more arguments>)
        File "C:/users/X/_bazel_X/fiijdbw7/external/io_bazel_rules_dotnet/dotnet/private/dotnet_toolchain.bzl", line 31, in toolchain.get_dotnet_runner
                fail(<1 more arguments>)
Could not find mono executable in dotnet_sdk (mono_bin)
ERROR: Analysis of target '//:a.exe' failed; build aborted: Analysis of target '//:a.exe' failed; build aborted
INFO: Elapsed time: 3.893s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (22 packages loaded, 838 targets configured)
```
using the current HEAD of master. 
@tomaszstrejczek I've modified your example to use .NET Core for repro ([a.zip][a.zip]) - The one you posted _works_ for .NET Framework (I tested it for 4.7.2).

[a.zip](https://github.com/bazelbuild/rules_dotnet/files/4108928/a.zip)

**Comment by tomaszstrejczek** [comment]
The latest version dropped support for .NET Framework and Mono. The problem should not exist anymore.
