### ISSUE TITLE
Referencing AspNetCore dlls in .NET Core 3.0.100 SDK

### ISSUE THREAD

**Issue by ztl8702** [bazelbuild/rules_dotnet#151]
It seems that AspNetCore 3.0 is [no longer shipped as nuget packages](https://stackoverflow.com/a/58126758) but rather inside the SDK. 

i.e. it is located in `shared/Microsoft.AspNetCore.App/3.0.0`.

To reference it, I assume we need to add `core_stdlib` rules for Microsoft.AspNetCore.App DLLs to  https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/stdlib.core/macro.bzl ?

@tomaszstrejczek  can you show me how you created [those rules](https://github.com/bazelbuild/rules_dotnet/blob/eaa368a35b6d0629a240ba6422f210e9dec1c241/dotnet/stdlib.core/macro.bzl#L9-L174) for Microsoft.NETCore.App DLLs (and their deps)? Was that by hand or using some tools? I would love to help.

**Comment by codebreach** [comment]
any way I can help with this? we also need this support!

**Comment by tomaszstrejczek** [comment]
The support for ASP.NET Core build is now available on master. See https://github.com/bazelbuild/rules_dotnet/tree/master/tests/examples/aspnetcore

**Comment by ztl8702** [comment]
Cool. Thanks!
