### ISSUE TITLE
nuget2bazel generates dependencies to inexistant targets

### ISSUE THREAD

**Issue by plule-ansys** [bazelbuild/rules_dotnet#173]
Hello, I'm trying to use nuget2bazel to integrate a dependency to GRPC with the net462 .Net Framework, the generated declaration contains dependencies to the following targets:

 - @io_bazel_rules_dotnet//dotnet/stdlib.net:net462_system.threading.tasks.extensions.dll
 - @io_bazel_rules_dotnet//dotnet/stdlib.net:net462_system.buffers.dll
 - @io_bazel_rules_dotnet//dotnet/stdlib.net:net462_system.numerics.vectors.dll

It happens using the 0.0.5 tag. A workaround is to remove these three entries in `tools/nuget2bazel/SdkList.cs`, which make it pulls the dependencies from nuget rather than trying to find them in the SDK, however I have no idea if that's a valid solution.

I have created a minimal reproduction here: https://github.com/plule-ansys/rules_dotnet_memory_deps

It contains the code generated in this situation, and a patch containing the workaround described above.

Thanks!

**Comment by tomaszstrejczek** [comment]
Try using rules_dotnet from master branch. It should be fixed there.

**Comment by plule-ansys** [comment]
Thank you for your answer Tomasz. The situation is improved in master branch: All the nuget dependencies are properly generated, however other entries are still depending to "@io_bazel_rules_dotnet//dotnet/stdlib.net:net462_{package}.dll" rather than the nuget package "@{package}//:net462_net". In my repro I see it on:

 - system.buffers
 - system.numerics.vectors
 - system.runtime.compilerservices.unsafe
 - system.threading.tasks.extensions
 - system.threading.channels

Making these replacements solves all the build-time issues. I have updated the reproduction repo.

**Comment by tomaszstrejczek** [comment]
Fixed in master. I've also added a working example based on your minimal repro: https://github.com/bazelbuild/rules_dotnet/tree/master/docs/examples/grpc

**Comment by plule-ansys** [comment]
@tomaszstrejczek This is great thanks a lot
