### ISSUE TITLE
How to add aribitrary files as EmbeddedResource ?

### ISSUE THREAD

**Issue by marcino239** [bazelbuild/rules_dotnet#179]
Hello!

How can I add a non-resx file to the target?  I.e. I am trying to replicate this msbuild directive:

```
  <ItemGroup>
    <EmbeddedResource Include="file.name" />
  </ItemGroup>
```

The doc for core_resx says that "Only .resx files are permitted"

Thanks,
marcino239

**Comment by tomaszstrejczek** [comment]
Use core_resource instead. For example:
core_resource(
    name = "resource1",
    src = "src/NUnitFramework/tests/TestImage1.jpg",
    identifier = "NUnit.Framework.TestImage1.jpg",
)

Then provide them in resource attribute:
core_library(
   ...
    resources = [
        ":resource1",
    ],
)

**Comment by marcino239** [comment]
Great - thanks.  Is there a way to specify glob list as sources ?

**Comment by marcino239** [comment]
So I did this and it works well.  However the core_resource rule does not expose visibility argument and all resources are showing up as public
```
TEST_DATA = [
        "TestData/file1",
        "TestData/file2",
   ]

core_xunit_test(
    name = "test.dll",
    srcs = glob(["**/*.cs"], ["bin/**", "obj/**" ]),
    nowarn = [ "CS1701" ],
    resources = [ ":testdata{}".format( i ) for i in range(len(TEST_DATA)) ],
    deps = [
        "@newtonsoft.json//:netcoreapp3.1_core",
        "@xunit.assert//:netcoreapp3.1_core",
        "@xunit.extensibility.core//:netcoreapp3.1_core",
        "@xunit.extensibility.execution//:netcoreapp3.1_core",
    ],
)

[core_resource(
    name = "testdata{}".format( i ),
    visibility = ['//visibility:private'],
    src = TEST_DATA[i],
    identifier = "test.{}".format( TEST_DATA[i].replace( "/", "." ) )
) for i in range(len(TEST_DATA)) ] 

```
