### ISSUE TITLE
Support nuget packages with multiple target frameworks.

### ISSUE THREAD

**Issue by zaphar** [bazelbuild/rules_dotnet#18]
Some nuget packages support multiple frameworks using the following convention in their directory structure.

lib/net{40,45}/... 

Unfortunately the nuget package manager doesn't really support handling this for you. Which means we need to intelligently detect when there is a net\* directory and handle it correctly. If we don't then the dotnet compiler will complain about multiple definitions for symbols as it pulls in all the assemblies at once.

**Comment by tomaszstrejczek** [comment]
https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/workspace.rst#nuget_package and https://github.com/bazelbuild/rules_dotnet/blob/master/tools/nuget2bazel/README.rst fix the issue.
