### ISSUE TITLE
Building dotnetcore2.1 that uses netstandard2.0 fails

### ISSUE THREAD

**Issue by erezbo** [bazelbuild/rules_dotnet#188]
Creates system package collisions:

See attached files
[WORKSPACE.txt](https://github.com/bazelbuild/rules_dotnet/files/4856871/WORKSPACE.txt)
[BUILD.txt](https://github.com/bazelbuild/rules_dotnet/files/4856875/BUILD.txt)
[project.csproj.txt](https://github.com/bazelbuild/rules_dotnet/files/4856876/project.csproj.txt)
[output.txt](https://github.com/bazelbuild/rules_dotnet/files/4856877/output.txt)

**Comment by paveli-d9** [comment]
Hi,

I would like to provide more info to the above:

Currently, we are using "dotnet build/publish" command to build our projects on os-x machines, which uses csproj file.

We are trying to convert existing csproj files to bazel build files and start using bazel.
Some of our projects are netstandard2.0 libraries, like the example in project.csproj.txt.

So, first we are using the nuget2buzel tool from the repo to create nuget_rules in workspace file, by running it as below for each reference in csproj file and its dependancies:
bazel run //tools/nuget2bazel:nuget2bazel.exe -- add -p <directory> <package_name> <package_version>
Then, we are creating the attached BUILD file.

Unfortunately, we are struggling to configure the dependancies. If we do not provide "@io_bazel_rules_dotnet//dotnet/stdlib.core/v2.1.200:libraryset" as dependancy we get the error that some basic definitions, like System.Object are missing. when we provide the "@io_bazel_rules_dotnet//dotnet/stdlib.core/v2.1.200:libraryset" as dependancy we get the error about multiple definitions.

What is the correct way to define the dependancies?
---------------------
Platform: MacOs Catalina 10.15.4
.Net core SDK 2.1
net-standard library 2.0

Please let us know if additional info is required.

Thank you in advance.

**Comment by tomaszstrejczek** [comment]
See #189 for an example of using netstandard and core assemblies together.

**Comment by erezbo** [comment]
This a trimmed down example of one of our projects that throws an error:

Settings (see "My.Project.csproj"):
sdk version 2.1.503
netstandard version 2.0.3
System.Net.Primitives version 4.3.1

My Bazel BUILD & WORKSPACE files are included.

Build fails due to System.Net.Primitives version conflict (see "error.txt").

What is the correct way to configure BUILD & WORKSPACE?

[BUILD.txt](https://github.com/bazelbuild/rules_dotnet/files/5049925/BUILD.txt)
[error.txt](https://github.com/bazelbuild/rules_dotnet/files/5049926/error.txt)
[My.Project.csproj.txt](https://github.com/bazelbuild/rules_dotnet/files/5049927/My.Project.csproj.txt)
[WORKSPACE.txt](https://github.com/bazelbuild/rules_dotnet/files/5049928/WORKSPACE.txt)

**Comment by tomaszstrejczek** [comment]
Fixed in #196
