### ISSUE TITLE
Use different source(s) with nuget2bazel tool

### ISSUE THREAD

**Issue by jwillebrands** [bazelbuild/rules_dotnet#191]
Hi,

We've recently had to expand our codebase with a little dotnet and, since we are using Bazel for everything else, were hoping to do the same here. We tend to pull most of our packages from an Azure artifact feed. Is there any way that we can use a different source in combination with the nuget2bazel tool? I found that the nuget_package rule does support specifying the source, but so far, I've not been able to find a way to have the tool support that as well.

**Comment by tomaszstrejczek** [comment]
No, it's not possible at the moment

**Comment by tomaszstrejczek** [comment]
I've started working on it.

**Comment by tomaszstrejczek** [comment]
Fixed in #192

**Comment by jwillebrands** [comment]
Awesome. Will give it a spin. Thanks a lot!
