### ISSUE TITLE
Dockerizing Dotnet Aspnet Exe

### ISSUE THREAD

**Issue by heynemann** [bazelbuild/rules_dotnet#193]
Hi, first of all thank you so much for these rules. You all rock!

I'm up to speed with having a rest and graphql asp.net APIs up and running: YAY!

Now I'm trying to dockerize them after build, so later on I can push them to our docker repo. I adapted some of the stuff in https://github.com/scalio/bazel-dotnetcore-starter for starting out.

The problem I have now is that, even though I can build the images, there's no way to run. If I build the image with:

```
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "core_binary")
load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_image",
)

core_binary(
    name = "rest-cli.exe",
    srcs = glob([
        "*.cs",
        "Controllers/*.cs",
    ]),
    deps = [
        "//rest/Controllers/Utils:rest-controllers-utils.dll",
        "@io_bazel_rules_dotnet//dotnet/stdlib.core:Microsoft.AspNetCore.App",
        "@io_bazel_rules_dotnet//dotnet/stdlib.core:libraryset",
    ],
    visibility = ["//visibility:public"],
)

container_image(
    name = "rest-cli-docker",
    base = "@aspnetcore//image",
    files = [":rest-cli.exe"],
    entrypoint = ["dotnet", "rest-cli.exe"],
)
``` 

I get an error like this:

```
$ bazel run //rest:rest-cli-docker && docker run bazel/rest:rest-cli-docker

INFO: Analyzed target //rest:rest-cli-docker (1 packages loaded, 4 targets configured).
INFO: Found 1 target...
Target //rest:rest-cli-docker up-to-date:
  bazel-bin/rest/rest-cli-docker-layer.tar
INFO: Elapsed time: 1,478s, Critical Path: 1,01s
INFO: 5 processes: 5 darwin-sandbox.
INFO: Build completed successfully, 7 total actions
INFO: Build completed successfully, 7 total actions
Loaded image ID: sha256:f32ba0f27df9b5c591a359991128abd736f6202140ca3f3a1f2750fb6db7d431
Tagging f32ba0f27df9b5c591a359991128abd736f6202140ca3f3a1f2750fb6db7d431 as bazel/rest:rest-cli-docker
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /rest-cli.runtimeconfig.json file specifying the appropriate framework.
```

After some digging, I found out that I could include the `runtimeconfig.json` file and tried it as well:

```
container_image(
    name = "rest-cli-docker",
    base = "@aspnetcore//image",
    files = [":rest-cli.exe", "//rest:rest-cli.runtimeconfig.json"],
    entrypoint = ["dotnet", "rest-cli.exe"],
)
```

`rest-cli.runtimeconfig.json`:

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.6"
    }
  }
}
```

With this configuration I get the following error:

```
INFO: Analyzed target //rest:rest-cli-docker (1 packages loaded, 5 targets configured).
INFO: Found 1 target...
Target //rest:rest-cli-docker up-to-date:
  bazel-bin/rest/rest-cli-docker-layer.tar
INFO: Elapsed time: 1,521s, Critical Path: 1,08s
INFO: 5 processes: 5 darwin-sandbox.
INFO: Build completed successfully, 7 total actions
INFO: Build completed successfully, 7 total actions
Loaded image ID: sha256:00637d921f791f7c4964f6925837d1522c9d8ad1cdca0a95fa6d345543484f16
Tagging 00637d921f791f7c4964f6925837d1522c9d8ad1cdca0a95fa6d345543484f16 as bazel/rest:rest-cli-docker
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.Extensions.Hosting.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

The relevant part of my Workspace:

```
workspace(name = "test")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

# docker rules and setup
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker",
    commit = "9bfcd7dbf0294ed9d11a99da6363fc28df904502",
    shallow_since = "1596824487 -0400",
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("@io_bazel_rules_docker//repositories:pip_repositories.bzl", "pip_deps")

pip_deps()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "dotnet",
    registry = "mcr.microsoft.com",
    repository = "dotnet/core/runtime",
    tag = "3.1",
)

container_pull(
    name = "aspnetcore",
    registry = "mcr.microsoft.com",
    repository = "dotnet/core/aspnet",
    tag = "3.1",
)

# end of docker rules and setup

# dotnet rules and setup
git_repository(
    name = "io_bazel_rules_dotnet",
    remote = "https://github.com/bazelbuild/rules_dotnet",
    commit = "5a20827ef84be2c66be06a8840bc92d32f644d5e",
    shallow_since = "1596122608 +0200",
)

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")

dotnet_repositories()

load(
    "@io_bazel_rules_dotnet//dotnet:defs.bzl",
    "core_register_sdk",
    "dotnet_register_toolchains",
    "dotnet_repositories_nugets",
    "nuget_package",
)

dotnet_register_toolchains()

dotnet_repositories_nugets()

core_register_sdk(
    "v3.1.100",
    name = "core_sdk",
)

### Generated by the tool
```

Does anyone with more experience can help?

**Comment by tomaszstrejczek** [comment]
I assume that you tried bazel run //rest:rest-cli.exe and it worked (without docker).
The docker image doesn't work because it requires many other files to run. See the folder bazel-bin/rest/rest-cli.exe. All files and subdirectories except *.runfiles are required to run rest-cli.exe. They contain both dotnet runtime and all dependencies of rest-cli.exe

**Comment by heynemann** [comment]
I did, now I'm having some trouble trying to understand how to reference the files in `bazel-bin` in my `container_image` target. Any hints?
Sorry for the lack of experience with bazel and thanks again for the support!

**Comment by heynemann** [comment]
Just another piece of information that may tell what's going wrong, I'm building on a mac os device and docker is running linux.

**Comment by tomaszstrejczek** [comment]
Try using pkg_tar. For example:
`
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "hello_core",
    srcs = [":v3.1.100_hello-core.exe"],
    include_runfiles = True,
    mode = "0755",
    remap_paths = {"/libhostfxr.dylib": "/host/fxr/3.1.0/libhostfxr.dylib"},
)
`

I have never tried to build linux binaries on osx platform. Rules_dotnet most likely will not work in cross-compilation scenario.

**Comment by jwnewman12** [comment]
I can comment that _it does work_ in such a scenario. We have both macOS and Linux users building Linux images for aspnet core, that work well now. It looked like all of the toolchain work was in there already.

With the above snippet, there is one issue, `include_runfiles = True`, results in the Darwin SDK .dll files landing in the package. This leads to a "BadImageFormatException", as those files have to be the Linux versions for Docker - the Darwin files cannot go in there. Instead:

- Use `dotnet/aspnet` for the base image, not `dotnet/core/runtime` (as we were at first).
- Drop include_runfiles, but then list your transitive lib deps and nuget packages, but not the stdlibs (these are in the base image).
- Use  `"@io_bazel_rules_dotnet//dotnet/stdlib.core:libraryset"` and `"@io_bazel_rules_dotnet//dotnet/stdlib.core:Microsoft.AspNetCore.App"` in the core_library / core_binary deps (not the old 2.2x nuget packages with similar names (probably obvious, but wasn't for me at first).
- Set `package_dir = "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.10/"` - so your app lives next to the asp dlls (there may be other ways to reference them and stay in your directory of choice).
- It seems good practice to make a separate `core_binary` for the image, that ends in `.dll` as most examples show the entry point being`["dotnet", "your-app.dll"]`. Or, just use the standalone `.exe` in the entry point, your choice.
- In the container_image, set `entrypoint = ["dotnet", "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.10/your-app.dll"]`.
- Include `:your-app.runtime.config.json` in the package as described above.

If this would be useful to add to the examples I can provide a few snippets or a PR.

Note we seem to be fine with using sandbox mode - I've never once set the flag and everything is ok in the sandbox. We are only building netcore on Linux, Mac, and WSL.

Also, the docs mention "the name must end in .exe" or "the name must end in .dll". This seems to partially true - our package names disregard this, and we instead use `out = "app.exe"` or `out = "lib.dll"` everywhere. This produces sane dotnet artifacts and allows our labels to be consistent with other projects.
