### ISSUE TITLE
Xamarin.ios / Xamarin.android support?

### ISSUE THREAD

**Issue by J-Swift** [bazelbuild/rules_dotnet#194]
Thanks for the efforts here, its great that progress is being made! I have only smoketested a bit of bazel and these rules, but the initial results are exciting in terms of build times and build management.

I am currently trying to replicate a `msbuild`/`csproj` based monorepo setup that I am using for app development (you can see the gist of the setup [here](https://gist.github.com/J-Swift/1ca7ec1c7af8ab89f316f67a7d1df623)). There are a few different ways that projects are built in there:

- `netstandard` shared library. I seem to be able to generate this using the rules just fine
- Platform specific mono-based application projects. These are standard `Xamarin.iOS` and `Xamarin.Android` builds. I'm not sure if it makes sense to convert these yet, I had planned on just keeping these as msbuild/csproj based for now and import bazel artifacts as DLLs. At least until something like #12 is implemented.
- Multi-targeted shared library with platform specific code. **This is what I'm trying to work through now**. I think that there will need to be native rules code implemented to locate and import the appropriate framework DLLs similar to how mono is done. For example, I'm on a mac and the android/iOS files are located at `/Library/Frameworks/Xamarin.Android.framework` and `/Library/Frameworks/Xamarin.iOS.framework` respectively.

Am I correct in assuming that it isn't currently possible to build for ios/android? I should warn that I am very naive to all of `bazel`, `msbuild`, and everything around these build systems. I only moved to dotnet by way of `Xamarin`, as I am originally a native app developer.

If this is currently possible, it would be good to have an example in the docs somewhere. If you outline the steps I'm happy to work on that for you.

**Comment by tomaszstrejczek** [comment]
Xamarin iOS and Android builds are not supported and will not work with rules_dotnet.

**Comment by J-Swift** [comment]
Understood @tomaszstrejczek, thank you for the follow up. Just to fully understand, are ios/android not supported _currently_ or are they never going to be supported?

**Comment by tomaszstrejczek** [comment]
Any pull request is more than welcome :) I don't have enough knowledge to add support for Xamarin.

**Comment by J-Swift** [comment]
OK perfect. I'm on the other side of the spectrum (only knowing ios/android) and so I'll keep an eye on these rules over time and hopefully find somewhere I can inject some expertise to hook the two sides together.
