### ISSUE TITLE
The nuget_package format you give in the README.md is outdated (for bazel 3.5)

### ISSUE THREAD

**Issue by nimrodpar** [bazelbuild/rules_dotnet#197]
Should be: 

```
nuget_package(
    name = "newtonsoft.json",
    # ...
    core_lib = {"netstandard2.0":  "lib/netstandard2.0/Newtonsoft.Json.dll"},
    # ...
    core_files = { "netstandard2.0":  [
        "lib/netstandard2.0/Newtonsoft.Json.dll",
        "lib/netstandard2.0/Newtonsoft.Json.xml",
    ]},
    #...
)
```

**Comment by nimrodpar** [comment]
Also, if someone can specify the `nuget_package` for `using Microsoft.CodeAnalysis;` and `using Microsoft.CodeAnalysis.CSharp;`, I would be eternally grateful.

**Comment by nimrodpar** [comment]
Just continuing the conversation with myself..when i try to run the bazel built executable is get:

```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=
4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The module was expected
 to contain an assembly manifest.
```

Thoughts?

**Comment by tomaszstrejczek** [comment]
Do you use bazel run command?

**Comment by nimrodpar** [comment]
> Do you use bazel run command?

Yes. It gives a 'no SDK found' error (core SDK 3.1 is installed). Tried on WSL2 and on a Ubuntu 18 container

**Comment by nimrodpar** [comment]
p.s. i found the nuget declarations for using `Microsoft.CodeAnalysis` that were able to `bazel build` successfully:

```
nuget_package(
    name = "microsoft.codeanalysis.csharp",
    package = "microsoft.codeanalysis.csharp",
    version = "3.7.0",
    core_lib = {
        "netcoreapp3.1": "lib/netcoreapp3.1/Microsoft.CodeAnalysis.CSharp.dll"
    },
    core_files = {
        "netcoreapp3.1": [
            "lib/netcoreapp3.1/Microsoft.CodeAnalysis.CSharp.dll",
            "lib/netcoreapp3.1/Microsoft.CodeAnalysis.CSharp.xml"
        ]
    }
)

nuget_package(
    name = "microsoft.codeanalysis.common",
    package = "microsoft.codeanalysis.common",
    version = "3.7.0",
    core_lib = {
        "netcoreapp3.1": "lib/netcoreapp3.1/Microsoft.CodeAnalysis.dll"
    },
    core_files = {
        "netcoreapp3.1": [
            "lib/netcoreapp3.1/Microsoft.CodeAnalysis.dll",
            "lib/netcoreapp3.1/Microsoft.CodeAnalysis.xml"
        ]
    }
)
```

Use them with: `deps = [ "@microsoft.codeanalysis.csharp//:netcoreapp3.1_core",  "@microsoft.codeanalysis.common//:netcoreapp3.1_core", ]`.

`bazel run` still does not work, and when I run the exe directly i get the aforementioned `Could not load file or assembly 'System.Runtime, Version=4.2.2.0` error.

**Comment by tomaszstrejczek** [comment]
Usually the error "Could not load file or assembly 'System.Runtime, Version=x.y.z.v'" means that there is a mismatch between versions of System.Runtime used by nuget assembly and by other code.
rules_dotnet can resolve some mismatches if enough information is provided. 
If you run:
`
bazel run --spawn_strategy=standalone @io_bazel_rules_dotnet//tools/nuget2bazel:nuget2bazel.exe -- add -p c:/temp microsoft.codeanalysis.csharp 3.7.0 -m microsoft.codeanalysis.csharp.dll
`
you will see in generated c:/temp/WORKSPACE that the rule microsoft.codeanalysis.csharp defines multiple dependencies which should help rules to resolve versions.

**Comment by purkhusid** [comment]
We are redoing the NuGet handling on the `next` branch. Closing.
