### ISSUE TITLE
Preserving runfiles folder architecture

### ISSUE THREAD

**Issue by plule-ansys** [bazelbuild/rules_dotnet#201]
Hello, the targets passed in the `data` attribute of a library, test or binary are copied near the executable rather than provided with the Bazel folder architecture described by the [data bazel doc](https://docs.bazel.build/versions/master/build-ref.html#data). A file located in "some_folder/file" will be available as "file" rather than "some_foder/file" at runtime. This copy is also a concern with large data.

Reproduction:

 - Extract [rules_dotnet_data.zip](https://github.com/bazelbuild/rules_dotnet/files/5415201/rules_dotnet_data.zip)
 - `bazel run //:Program.dll`

The archive contains a "no design" patch preserving the data argument for tests and binaries to make the program work. I *think* the core issue is easy to fix, while even preserving the copy feature (like separating the `data` attribute from `data_to_copy_near_executable`), but it's a behavior change and might have unexpected other consequences.

**Comment by purkhusid** [comment]
A runfiles library with examples has been added to the `next` branch.
