### ISSUE TITLE
Does this project still in active development?

### ISSUE THREAD

**Issue by leolcao** [bazelbuild/rules_dotnet#203]
I want to use bazel with this dotnet rule to build .net/.netcore 3.1/.net 5 applications and libraries, and I am doing some estimation from this project.

So for, I find some issues, such as the 'dotnet_nuget_new' doesn't support nuget V3 API yet and others.

Then I want to ask the question as title. Does this project still alive?

**Comment by tomaszstrejczek** [comment]
AFAIK I'm the only active contributor to the project. I do it in my spare time.
