### ISSUE TITLE
Hello Worlds failing on Windows 10

### ISSUE THREAD

**Issue by warriorstar-orion** [bazelbuild/rules_dotnet#204]
Hello, and thanks for all your work.

The repo at https://github.com/warriorstar-orion/bugs_dotnet_sdk_helloworld should be a ideal repro case.

The repro:
```
PS D:\ACS> bazel --version
bazel 3.7.1

PS D:\ACS> systeminfo | select -first 10

Host Name:                 HETERODOX
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00330-80000-00000-AA856

PS D:\ACS> bazel --bazelrc=/dev/null build :core_a.exe
ERROR: C:/users/wso/_bazel_wso/on6osib7/external/io_bazel_rules_dotnet/BUILD:11:18: every rule of type core_context_data implicitly depends upon the target '@core_sdk//:runner', but this target could not be found because of: no such package '@core_sdk//': The repository '@core_sdk' could not be resolved
ERROR: Analysis of target '//:core_a.exe' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.445s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

PS D:\ACS> bazel --bazelrc=/dev/null build :net_a.exe
ERROR: C:/users/wso/_bazel_wso/on6osib7/external/io_bazel_rules_dotnet/BUILD:6:20: every rule of type dotnet_context_data implicitly depends upon the target '@dotnet_sdk//:csc', but this target could not be found because of: no such target '@dotnet_sdk//:csc': target 'csc' not declared in package '' defined by C:/users/wso/_bazel_wso/on6osib7/external/dotnet_sdk/BUILD.bazel
ERROR: Analysis of target '//:net_a.exe' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.386s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
PS D:\ACS>
```

Additionally, I don't suppose the naming of the `WORKSPACE` rules can be changed? I'm not a .NET programmer but for me it's confusing to know there are three toolchains: .NET Core, .NET Framework, and Mono Framework, but the related rules are `core_*`, `net_*`, and `dotnet_*` instead of (to my naive understanding) `dotnet_core_*`, `dotnet_framework_*`, and `mono_framework_*`. Is there room for improvement with these names or am I misunderstanding their meaning?

Thanks again!

**Comment by tomaszstrejczek** [comment]
Could you test it with the latest version (0.0.6)? Please note that .NET Framework support is dropped.

**Comment by warriorstar-orion** [comment]
Excellent work! A clean `bazel run //:core_a.exe` works exactly as expected.

The exact changes are made here: https://github.com/warriorstar-orion/bugs_dotnet_sdk_helloworld/commit/046392c34d72ea2f5c01e36687c3b9e7b20eb59b

Platform information is the same as above if you want to point to this as a Hello World for the future.
