### ISSUE TITLE
.Net 5 Support

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_dotnet#210]
Would it be possible to add .Net 5 support? I tried looking into it but I did not figure out how to generate the generate.bzl and generate2.bzl files that are there for each version.

**Comment by purkhusid** [comment]
Also, would be nice if there was documentation on how to add new versions

**Comment by samhowes** [comment]
Agreed. I have been looking at `dotnet/stdlib.core/*/generated.bzl` files and, not being very familiar with details of bazel, wondering how they are generated so I could try out .NET 5, and why exactly they need to be there.

**Comment by purkhusid** [comment]
I think I figured this out and I have a PR here: https://github.com/bazelbuild/rules_dotnet/pull/212

**Comment by jimmyhoran** [comment]
Looks like this was addressed with pr https://github.com/bazelbuild/rules_dotnet/pull/240. Can we close this issue now?
