### ISSUE TITLE
Toolchain error when using the new F# rules

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#222]
I'm not sure if I have missed a step here? 

`WORKSPACE`

```python
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
  name = "io_bazel_rules_dotnet",
  remote = "https://github.com/bazelbuild/rules_dotnet",
  branch = "master",
)

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")

dotnet_repositories()

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "dotnet_register_toolchains", "dotnet_repositories_nugets")

dotnet_register_toolchains()
dotnet_repositories_nugets()
```
`BUILD`

```python
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "fsharp_binary")

fsharp_binary(
  name = "demo",
  srcs = [
    "Program.fs",
  ],
)
```

```bash
$ bazel --version                                                                                                            
bazel 4.0.0

$ bazel build --host_platform //dotnet/toolchain:linux_amd64_2.2.402 --platforms //dotnet/toolchain:linux_amd64_2.2.402 //...

ERROR: While resolving toolchains for target //:demo: com.google.devtools.build.lib.packages.BuildFileNotFoundException: no such package 'dotnet/toolchain': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.

ERROR: Analysis of target '//:demo' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileNotFoundException: no such package 'dotnet/toolchain': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```

Bazel `4.0.0` and Ubuntu Linux.

**Comment by njlr** [comment]
Some progress...

`.bazelrc`

```
build --host_platform @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100
build --platforms @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100
```

Then

```bash
$ bazel build //...                                                                 
INFO: Analyzed target //:demo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:demo up-to-date:
  bazel-bin/demo/demo
  bazel-bin/demo/demo_0.exe
INFO: Elapsed time: 0.173s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

However, it does not run:

```bash
$ bazel run //:demo      
INFO: Analyzed target //:demo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:demo up-to-date:
  bazel-bin/demo/demo
  bazel-bin/demo/demo_0.exe
INFO: Elapsed time: 0.154s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

```bash
$ dotnet --list-sdks
3.1.406 [/usr/share/dotnet/sdk]
5.0.103 [/usr/share/dotnet/sdk]
```

Although I didn't think local tools were required to run Bazel targets.

**Comment by tomaszstrejczek** [comment]
I think bazel run also requires --host_platform and --platform.
rules_dotnet do not expect any SDK to be installed. It downloads it based on selected platform.

**Comment by njlr** [comment]
> I think bazel run also requires --host_platform and --platform.
> rules_dotnet do not expect any SDK to be installed. It downloads it based on selected platform.

Yes the build command (copied from README) was `bazel build --host_platform //dotnet/toolchain:linux_amd64_2.2.402 --platforms //dotnet/toolchain:linux_amd64_2.2.402 //...`

**Comment by tomaszstrejczek** [comment]
I'm referring to the problem with executing bazel run //:demo.

Have you tried 
`bazel run --host_platform @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100  --platforms @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100 //:demo`
?

**Comment by njlr** [comment]
```bash
$ bazel run --host_platform @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100 --platforms @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100 //:demo

INFO: Analyzed target //:demo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:demo up-to-date:
  bazel-bin/demo/demo
  bazel-bin/demo/demo_0.exe
INFO: Elapsed time: 0.084s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

**Comment by purkhusid** [comment]
> ```shell
> $ bazel run --host_platform @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100 --platforms @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100 //:demo
> 
> INFO: Analyzed target //:demo (0 packages loaded, 0 targets configured).
> INFO: Found 1 target...
> Target //:demo up-to-date:
>   bazel-bin/demo/demo
>   bazel-bin/demo/demo_0.exe
> INFO: Elapsed time: 0.084s, Critical Path: 0.00s
> INFO: 1 process: 1 internal.
> INFO: Build completed successfully, 1 total action
> INFO: Build completed successfully, 1 total action
>   It was not possible to find any installed .NET Core SDKs
>   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
>       https://aka.ms/dotnet-download
> ```
> 
> Expected output is:
> 
> > Hello world from F#

@njlr You don't happen to be using any form of remote execution? I got the same error when trying to build rules_dotnet targets with remote execution. 

Can you try running the same command for a C# library and see if it comes with the same error?

**Comment by purkhusid** [comment]
@njlr I figured this out. You are missing the `.exe` extension in the target name. It is required that libraries have `.dll` extensions and executables `.exe`.

I'm not sure if this is something that could be removed now that the rules only support .Net Core. @tomaszstrejczek would know more about that.

**Comment by njlr** [comment]
Success! Thanks @purkhusid 

The winning combination is:

`.bazelrc`

```
build --host_platform @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100
build --platforms @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100
```

`WORKSPACE`

```python
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
  name = "io_bazel_rules_dotnet",
  remote = "https://github.com/bazelbuild/rules_dotnet",
  branch = "master",
)

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")

dotnet_repositories()

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "dotnet_register_toolchains", "dotnet_repositories_nugets")

dotnet_register_toolchains()
dotnet_repositories_nugets()
```

`BUILD`

```python
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "fsharp_binary")

fsharp_binary(
  name = "demo.exe",
  srcs = [
    "Program.fs",
  ],
  deps = [
    "@core_sdk_stdlib//:libraryset",
  ],
)
```

Perhaps the rule `fsharp_binary` should throw if the name does not end in `.exe`, just as a temporary measure?

**Comment by purkhusid** [comment]
Yeah, might make sense to add a check. What do you think @tomaszstrejczek ?

**Comment by tomaszstrejczek** [comment]
@purkhusid Yes, it makes sense.

**Comment by purkhusid** [comment]
PR here: https://github.com/bazelbuild/rules_dotnet/pull/223
