### ISSUE TITLE
[Next] Update rules-proto-grpc once next branch is merged

### ISSUE THREAD

**Issue by aaliddell** [bazelbuild/rules_dotnet#225]
In recent versions you've switched to using toolchains and platforms for selecting the SDK version to be used. However, using a platform to resolve a single field in the toolchain is somewhat problematic for anyone who already has an existing platform, since it necessarily won't know about the SDK version.

Why were the config_settings not applied directly as constraints on the toolchain, rather than indirectly via the platforms? e.g `bazel build //... --@io_bazel_rules_dotnet//dotnet/toolchain:sdk_version=3.1.100` along with `target_settings` on the toolchain definitions to restrict the resolved toolchain to one that matches the SDK version config setting.

**Comment by purkhusid** [comment]
@aaliddell Do you have some examples of toolchains that are configured this way? E.g. how do I make a constraint conifgurable via a flag?

**Comment by purkhusid** [comment]
And also, is it possible to use incompatible target skipping when using the approach you mentioned? E.g. in repo there are targets that are only compatible with certain SDK versions.

**Comment by purkhusid** [comment]
These flags will be removed when we merge the `next` branch. I'm going to change this issue to track updating rules-proto-grpc once the `next` branch has been merged

**Comment by Place1** [comment]
Hello, is this issue about updating rules-proto-grpc so that the [csharp-grpc-library](https://rules-proto-grpc.com/en/latest/lang/csharp.html#csharp-grpc-library) etc. all work on the new `@rules_dotnet` instead of `io_bazel_rules_dotnet`?

**Comment by purkhusid** [comment]
Yes, we need to update rules_proto_grpc to use the latest release because we did multiple breaking changes recently
