### ISSUE TITLE
(Usability) Perhaps nuget2bazel should default to -p $PWD ?

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#229]
I'm not sure if `bazel run` passes the relevant info to the target executable, but it would significantly improve the onboarding experience if `-p $PWD` was the default. 

My first several attempts to use the tool put the config in the Bazel cache folder. 

What I tried:

```bash
bazel run @io_bazel_rules_dotnet//tools/nuget2bazel:nuget2bazel.exe -- add FSharp.Core 5.0.1
```

What 90% of users will intend:

```bash
bazel run @io_bazel_rules_dotnet//tools/nuget2bazel:nuget2bazel.exe -- add -p $PWD FSharp.Core 5.0.1
```

**Comment by purkhusid** [comment]
`nuget2bazel` will be deprecated when we merge the `next` branch. Closing
