### ISSUE TITLE
How do I add test data to fsharp_xunit_test?

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#235]
Repro here: https://github.com/njlr/bazel-xunit-test-data

Suppose I have a test that uses some resources:

```fsharp
module BazelXunitTestData

open Xunit
open System
open System.IO
open FsUnit.Xunit

[<Fact>]
let ``a is a`` () =
  "a" |> should equal "a"

[<Fact>]
let ``a file contains only a`` () =
  let path = "test-data/a.txt"
  let content = File.ReadAllText path

  content |> should equal "a"

```

```bash
$ tree ./test-data 
./test-data
└── a.txt
```

And a Bazel target:

```python
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "fsharp_xunit_test")

fsharp_xunit_test(
  name = "bazel_xunit_test_data.dll",
  srcs = [
    "Tests.fs",
  ],
  data = glob([
    "test-data/*.txt",
  ]),
  deps = [
    "@core_sdk_stdlib//:libraryset",
    "@fsharp.core//:lib",
    "@fsunit.xunit//:lib",
  ],
)
```

This works using `dotnet` by adding the test resources:

```xml
  <ItemGroup>
    <Content Include="test-data/**/*.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

But how do I do this with Bazel?

> System.IO.DirectoryNotFoundException : Could not find a part of the path .../553c0c5f76815781d3ffddebdcfcd179/sandbox/linux-sandbox/482/execroot/__main__/bazel-out/k8-fastbuild/bin/bazel_xunit_test_data.dll/bazel_xunit_test_data.dll_0.exe.runfiles/__main__/test-data/a.txt

**Comment by purkhusid** [comment]
I haven't taken a serious look but it appears that the data files are available  at the path `<name of target>/filename`e.g. in your example it works if you change the path to `bazel_xunit_test_data.dll/a.txt`

Apparently runfiles resolution is a complicated beast in bazel and most of the mature bazel rules have a runfiles library that can look up the runfiles e.g. https://github.com/bazelbuild/rules_go#how-do-i-access-testdata

**Comment by jwnewman12** [comment]
Instead of `data = `, try

```
 data_with_dirs = {
   ":test-data/file1.txt", "test-data",
   ":test-data/file2.txt", "test-data",
 }
```

in the xunit test. That requires listing each file .. but was the only way we could get it to work.  https://tomaszstrejczek.github.io/rules_dotnet/api.html#fsharp_xunit_test

**Comment by purkhusid** [comment]
We added a runfiles library in the `next` branch with examples. Closing this.
