### ISSUE TITLE
Fable output for F# targets (F# for web and Node.js)

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#236]
[Fable](fable.io/) is an F# to JavaScript compiler.

Here's how Fable works:

 1. Fetch Fable executable from Nuget `dotnet tool install Fable`
 2. Run Fable on a `.fsproj` file`dotnet fable ./my-project.fsproj`
 3. Fable generates a `.fs.js` file for every `.fs` file
 4. Additional standard library files are generated in `.fable` folder
 5. Nuget packages that contain `.fs` sources in a `fable` directory can also be understood by Fable
 6. Entry `.fs.js` file is given to Webpack to generate an application bundle

I can see how a Fable application might be built using a `genrule`. 

However, it would be a huge win if existing `fsharp_library` rules could also target Fable.

**Comment by purkhusid** [comment]
I'm not so sure that it makes sense to have the fable support in this repository since it will probably require a dependency on rules_nodejs for good interop since you would probably want to use the providers that rules_nodejs uses.

**Comment by njlr** [comment]
@purkhusid I think the Fable output might be consumed by rules from `rules_nodejs`, but I don't think this would require a dependency on them.

**Comment by purkhusid** [comment]
Doing some issue cleanup. Closing this since I don't plan on adding this and I'm not sure if it makes sense to add something like this to the repo because Fable uses a different toolchain.
