### ISSUE TITLE
Internal nugets clash with user nugets

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_dotnet#237]
The internal NuGet dependencies clash with the user specified NuGet packages.

E.g. ef I depend on Newtonsoft.Json in my application then it will clash with the Newtonsoft.Json that is declared here:
https://github.com/bazelbuild/rules_dotnet/blob/312dfb42f1e55dd7cbc5da0d1958de302b9643d1/dotnet/private/deps/nuget.bzl#L808

**Comment by purkhusid** [comment]
@tomaszstrejczek What would be your preferred fix to this? Should we just manually add an prefix to the internal dependencies or do we want to update the nuget2bazel program so that it allows the user to specify a prefix?

**Comment by tomaszstrejczek** [comment]
@purkhusid 
The problem is extensively discussed here: https://github.com/bazelbuild/bazel/issues/1952.
I like the option https://github.com/bazelbuild/bazel/issues/1952#issuecomment-272595447.
What's your opinion?

**Comment by purkhusid** [comment]
Can we not simply add a prefix to all the internal nugets so that they will be refernced as `@internal.newtonsoft.json` instead of `@newtonsoft.json`? Or is the problem more compilcated than that?

**Comment by purkhusid** [comment]
For nugets that are used for testing(xunit, nunit) we could create new toolchains that allow overriding the dependencies. `rules_scala` does something like that but I don't fully understand how it works since I have not read it thoroughly: https://github.com/bazelbuild/rules_scala/blob/master/testing/BUILD 

Nugets that are used by tools like nuget2bazel we could just add a prefix to the repository names like I mentioned in the comment above.

**Comment by tomaszstrejczek** [comment]
Adding a prefix to nuget2bazel dependencies seems a good idea.  

For xunit/nunit using a separate toolchain seems an overkill. I propose to modify dotnet_repositories_nugets() to include additional parameters. For example:
`
def dotnet_repositories_nugets(omit_xunit_console_runner=False):
  if not omit_xunit_console_runner:
    register_xunit_runner_console()
  ...
`
If a user calls  dotnet_repositories_nugets with omit_xunit_console_runner = True, then we do not declare @xunit_console_runner//:tool nuget dependency and assume that it will be declared/provided by the user with this exact name. 

Similar parameters could be used for other dependencies.
 
nuget2bazel could be modified to generate the if statement automatically.
