### ISSUE TITLE
Generate csproj/fsproj files from bazel targets

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_dotnet#239]
This is feature request which I might tackle myself later if nobody else does it.
I would like to be able to generate `.fsproj/csproj` files from the C#/F#` targets that are declared in my workspace.

This would make it easier to keep the IDE support working without having to manually maintain the `.fsproj/.csproj` files.

**Comment by njlr** [comment]
I made a start on this here: https://github.com/njlr/bazel2proj

There is still lots to do, but it works for the examples in the repo.

Long term I think it would be best to bring the tool into here?

**Comment by purkhusid** [comment]
Nice! It's definitely on the roadmap to ass BUILD/csproj/fsproj generation. I'll take a look at this once I'm off vacation.
