### ISSUE TITLE
rules_dotnet broken in Bazel downstream due to recent change to --toolchain_resolution_debug

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/rules_dotnet#243]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1984#1c810ab6-39c8-45d4-83c2-b2e2fbb8aa75
```
(02:10:54) ERROR: While resolving toolchains for target //tests/examples/example_tool:hello_tool.exe: no matching toolchains found for types //dotnet:toolchain_type_csharp_core
(02:10:54) ERROR: Analysis of target '//tests/examples/example_tool:hello_single_output' failed; build aborted: no matching toolchains found for types //dotnet:toolchain_type_csharp_core
```
https://buildkite.com/bazel/culprit-finder/builds/1319#f66fa0aa-c984-4b5c-8f84-b15918c8a5c7
Caused by https://github.com/bazelbuild/bazel/commit/fbf9f9d7d3228c2b7ddb1ff87605e90d8b56a3a9

**Comment by katre** [comment]
rules_dotnet needs to be updated, I'll send them a PR today.

**Comment by fweikert** [comment]
Great, thank you!

**Comment by fweikert** [comment]
Bazel auto-sheriff is convinced that the culprit here also caused this very different error: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1990#284aa31e-ee16-447a-af9f-7a30606fc5a5

**Comment by katre** [comment]
It is very unlikely that changing the way `--toolchain_resolution_debug` works caused an action conflict, but I will take a look.
