### ISSUE TITLE
How to call dependency for stdlib - dotnet core 

### ISSUE THREAD

**Issue by mrocheleau** [bazelbuild/rules_dotnet#254]
Getting lots of:
...error CS0518: Predefined type 'System.Boolean' is not defined or imported
...error CS0246: The type or namespace name 'Type' could not be found (are you missing a using directive or an assembly reference?)

type of errors on initial builds, I see references in old issues for "you need to declare dependencies for standard libraries" but they all reference a past structure of the repository, like these:

"@io_bazel_rules_dotnet//dotnet/stdlib.core:system.dll",
"@io_bazel_rules_dotnet//dotnet/stdlib.core:system.console.dll",

Where the current has dotnet/private/stdlib but that path has no BUILD files, but includes files that are the core versions.bzl.

How do we get the standard library dependencies for a csharp_library now?

Thank you!

**Comment by mrocheleau** [comment]
Any guidance here would be amazing, it SEEMS like all of the example code, and all of the README examples/guides show doing it the old way pre that "fully switched to platforms and toolchains" PR some months ago.  

How does one reference these new version specific bzl files (like:  https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/private/stdlib/3.1.100.bzl) to have system.dll be a dependency in a BUILD file?

**Comment by mrocheleau** [comment]
I was able to work around this by shoehorning in the core_sdk_linux_amd64_3.1.100 external repo and dep'ing system.dll from there, ie:  

deps = [
"@core_sdk_linux_amd64_3.1.100//:system.dll",
  ]

Along with a slew of other critical standard libs, but I see all of this defined elsewhere in the toolchain bits I just don't get how to get at them correctly.  Any help would be great to make this actually work correctly.

**Comment by purkhusid** [comment]
@mrocheleau You should just need to add `@core_sdk_stdlib//:libraryset` to the `deps` of you target to make the stdlib available.

**Comment by kreempuff** [comment]
@purkhusid Can this be put in the documentation somewhere? I just ran into this problem.

**Comment by purkhusid** [comment]
@kreempuff The master branch is going to be replaced by the `next` branch soon and this is not a thing there. The `next` branch has better examples.
