### ISSUE TITLE
Do not depend on a native toolchain

### ISSUE THREAD

**Issue by hsyed-dojo** [bazelbuild/rules_dotnet#265]
The native tools that are a part of the rules create a dependency on a native toolchain. We could replace them with platform specific scripts or create a release for them.

**Comment by jwnewman12** [comment]
We had to use a patch to delete the windows .c programs and just use the native `cp` / `ln` commands as `sh_binary`. Easy enough. 

There's also some issues with how the platforms & toolchain were setup I think. For instance, if you run `bazel query`, that command cannot specify a `--platforms` argument. The rules will then download _every single version_ of .netcore/framework/mono that they have listed internally. I don't think that's good.

When no platform is specified to drive cross compilation, it should just use the host platform. The version, should not have to be specified every single time. A reasonable default, and a new `--build_flag=6.0` could be added to control version.

We just patched it to delete everything but the latest netcore and hardcode it.

It's also not possible to query for `deps()` in this project, or any project using it.

**Comment by purkhusid** [comment]
@jwnewman12 Yeah, I had to the exact same thing to eliminate unnecessary downloads. I've been thinking about changing the toolchain setup to be a more standard and the end user should just register the toolchains that will be used. 

I've also been looking into how https://github.com/Brightspace/rules_csharp allows targeting different frameworks and might use it as an inspiration.

**Comment by tomdegoede** [comment]
I believe multi targetting from dotnet just uses the latest sdk but compiles against other versions' reference assemblies. It would remove a lot of complexity if we could just pin the sdk!

**Comment by purkhusid** [comment]
We no longer depend on the C toolchain on the `next` branch. Going to close this.
