### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by ax-meyer** [bazelbuild/rules_dotnet#266]
As usual (at least for me) when trying some new thing, I try to get the examples to run - but they won't run.

First problem: the `examples` folder is blacklisted in the `.bazelignore` file, so bazel refuses to build anything from the folder at all.

Second: Even after removing the ignore, it still won't bild - not even in the linked `gitpod`.

Error I am getting in the gitpod:

```
gitpod /workspace/rules_dotnet (master) $  bazel build --host_platform //dotnet/toolchain:linux_amd64_2.2.402 --platforms //dotnet/toolchain:linux_amd64_2.2.402 examples/grpc:service_proto
ERROR: Skipping 'examples/grpc:service_proto': error loading package 'examples/grpc': Unable to find package for @rules_proto_grpc//csharp:defs.bzl: The repository '@rules_proto_grpc' could not be resolved.
WARNING: Target pattern parsing failed.
ERROR: error loading package 'examples/grpc': Unable to find package for @rules_proto_grpc//csharp:defs.bzl: The repository '@rules_proto_grpc' could not be resolved.
INFO: Elapsed time: 0.301s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

This is not a great onboarding experience, and if I don't have a working minimal example to start from, I am very hesitant to try a tool / library - this usually forebodes a very tedious debugging workflow.

## Steps to reproduce
Click on gitpod link at top of readme.
Open `.bazelignore`, remove first line.
Execute `bazel build --host_platform //dotnet/toolchain:linux_amd64_2.2.402 --platforms //dotnet/toolchain:linux_amd64_2.2.402 examples/grpc:service_proto` in gitpod terminal.

**Comment by purkhusid** [comment]
Hey! The examples are each in their own self-contained workspace, you have to `cd` into each example directory and run `bazel` from within the directory. Hope that works for you!

**Comment by purkhusid** [comment]
Also, we recently removed support for unsupported versions of .Net. You can use .Net 5 with `--host_platform @io_bazel_rules_dotnet//dotnet/toolchain:5.0.201 --platforms @io_bazel_rules_dotnet//dotnet/toolchain:5.0.201`

**Comment by ax-meyer** [comment]
Still no luck:

```
gitpod /workspace/rules_dotnet/examples/grpc (master) $ bazel build --host_platform @io_bazel_rules_dotnet//dotnet/toolchain:5.0.201 --platforms @io_bazel_rules_dotnet//dotnet/toolchain:5.0.201 service_proto
ERROR: Traceback (most recent call last):
        File "/home/gitpod/.cache/bazel/_bazel_gitpod/a90af3886c1d1fd86a36199152469410/external/rules_proto_grpc/csharp/csharp_grpc_library.bzl", line 2, column 50, in <toplevel>
                load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "core_library")
Error: file '@io_bazel_rules_dotnet//dotnet:defs.bzl' does not contain symbol 'core_library' (did you mean 'core_libraryset'?)
ERROR: Skipping 'service_proto': error loading package '': in /home/gitpod/.cache/bazel/_bazel_gitpod/a90af3886c1d1fd86a36199152469410/external/rules_proto_grpc/csharp/defs.bzl: Extension file 'csharp/csharp_grpc_library.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: error loading package '': in /home/gitpod/.cache/bazel/_bazel_gitpod/a90af3886c1d1fd86a36199152469410/external/rules_proto_grpc/csharp/defs.bzl: Extension file 'csharp/csharp_grpc_library.bzl' has errors
INFO: Elapsed time: 0.110s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by purkhusid** [comment]
@ax-meyer The gRPC example was broken after some breaking changes done not too long ago and it was not part of the CI. I've fixed the example. Could you try pulling the latest changes and run `bazel test //... --host_platform=@io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_5.0.201 --platforms=@io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_5.0.201` within the `examples/grpc` directory ?

**Comment by ax-meyer** [comment]
Thanks, this fixed it! Works now on gitpod and my machine.
