### ISSUE TITLE
[Next] NuGet rules do not yet handle the runtimes folder

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#300]
Probably easiest to see the repro here: https://github.com/njlr/rules-dotnet-issue-native

Basically a Nuget package with native code (`MonoGame.Framework.DesktopGL`) does not get linked in correctly:

```bash
$ bazel run //:app

Unhandled exception. System.TypeInitializationException: The type initializer for 'Sdl' threw an exception.
 ---> System.Exception: Failed to load library: libSDL2-2.0.so.0
   at MonoGame.Framework.Utilities.FuncLoader.LoadLibraryExt(String libname)
   at Sdl.GetNativeLibrary()
   at Sdl..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.SdlGamePlatform..ctor(Game game)
   at Microsoft.Xna.Framework.GamePlatform.PlatformCreate(Game game)
   at Microsoft.Xna.Framework.Game..ctor()
```

**Comment by purkhusid** [comment]
@njlr This is known issue with the `next` branch. The new NuGet handling is not yet handling the `runtimes` folder. I'm planning on fixing this soon since I need this to be able to start using the `next` branch with my work monorepo.

I'm currently working on some dependency resolution fixing in the `next` branch and this was the next item I was going to tackle.

**Comment by njlr** [comment]
> @njlr This is known issue with the `next` branch. The new NuGet handling is not yet handling the `runtimes` folder. I'm planning on fixing this soon since I need this to be able to start using the `next` branch with my work monorepo.
> 
> I'm currently working on some dependency resolution fixing in the `next` branch and this was the next item I was going to tackle.

That's great to hear! I will give it a try once it's ready. 

Is this issue a dupe then?

**Comment by purkhusid** [comment]
No, let's keep this open to track this.

**Comment by njlr** [comment]
Works when using the branch in [this PR](https://github.com/bazelbuild/rules_dotnet/pull/303):

https://github.com/njlr/rules-dotnet-issue-native/tree/fix

**Comment by purkhusid** [comment]
This has now been fixed on  the `next` branch
