### ISSUE TITLE
[Next] binary target is missing from deps.json in publish_binary output

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#317]
The [deps.json spec](https://github.com/dotnet/sdk/blob/main/documentation/specs/runtime-configuration-file.md) shows `MyApp` in the `libraries` and `targets` dictionaries.

e.g.

```json
  "libraries": {
    "MyApp/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
```

and

```json
  "targets": {
    ".NETCoreApp,Version=v2.1": {
      "MyApp/1.0.0": {
        "dependencies": {
          "System.Banana": "1.0.0"
        },
        "runtime": {
          "MyApp.dll": {}
        },
        "compile": {
          "MyApp.dll": {}
        }
      },
```

However, the output of `publish_binary` does not have these entries. 

This is an issue for services that consume deps.json, such as AWS Lambda.

**Comment by purkhusid** [comment]
This is strange, maybe there is an regression in some recent change. I'm currently using the next branch with AWS Lambda and everything is working fine but I'm not using the latest `next` branch yet. I'll take a look as soon as possible.

**Comment by njlr** [comment]
In case it helps:

```starlark
publish_binary(
  name = "publish",
  binary = ":lambda",
  target_framework = "net6.0",
  self_contained = False,
  runtime_identifier = "linux-x64",
)

pkg_zip(
  name = "bundle",
  srcs = [
    ":publish",
  ],
  strip_prefix = "publish/publish/linux-x64",
)
```

**Comment by purkhusid** [comment]
@njlr A fix has been merged to the `next` branch. Could you test it on your repo and report back?

**Comment by njlr** [comment]
Yes, that seems to have done the trick!
