### ISSUE TITLE
csharp_binary gives "Too many levels of symbolic links" error on OS X

### ISSUE THREAD

**Issue by iainmerrick** [bazelbuild/rules_dotnet#34]
I'm having trouble getting the csharp_binary rule to work. I'm on OS X 10.12.

The rule seems to build OK, but when I run it I get this error:

```
$ bazel run :inklecate
INFO: Found 1 target...
Target //:inklecate up-to-date:
  bazel-bin/inklecate.exe
  bazel-bin/inklecate
INFO: Elapsed time: 0.066s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/inklecate
Cannot open assembly 'inklecate.exe': Too many levels of symbolic links.
ERROR: Non-zero return code '2' from command: Process exited with status 2.
```

The rule looks like this:

```
csharp_binary(
    name = "inklecate",
    main_class = "Ink.CommandLineTool",
    srcs = glob([
        "inklecate/*.cs",
        "inklecate/**/*.cs",
        "ink-engine-runtime/*.cs",
    ]),
    warn = 3, # Suppress documentation warnings
)
```

I've tried both `use_local_mono = True` and `False` but that doesn't seem to make a difference.

Full code is here: https://github.com/iainmerrick/ink

Further discussion on the Bazel mailing list: https://groups.google.com/forum/#!msg/bazel-discuss/M-qFbm0x6mY/KOy_ljc4AAAJ

**Comment by zaphar** [comment]
Interesting, if you execute the compiled assembly manually does it work?

**Comment by iainmerrick** [comment]
Running `./bazel-bin/inklecate` gives the same error.

Running `mono bazel-bin/inklecate.exe` works.

**Comment by iainmerrick** [comment]
Aha! Taking a closer look at the generated `inklecate` script, this looks bad:

    bazel-bin/inklecate.runfiles/__main__$ ls -a -l
    total 16
    drwxr-xr-x  5 iain  wheel  170 27 Oct 20:11 .
    drwxr-xr-x  5 iain  wheel  170 27 Oct 20:11 ..
    drwxr-xr-x  3 iain  wheel  102 27 Oct 20:11 external
    lrwxr-xr-x  1 iain  wheel  114 27 Oct 20:11 inklecate -> /private/var/tmp/_bazel_iain/3748381dda9ed83df4937428344e9aeb/execroot/ink/bazel-out/local-fastbuild/bin/inklecate
    lrwxr-xr-x  1 iain  wheel   13 27 Oct 20:11 inklecate.exe -> inklecate.exe

The `inklecate.exe` symlink inside runfiles is a self-reference.

**Comment by zaphar** [comment]
Yeah, sounds like the script generation is wrong there.

I'm not sure when I'll be able to tackle this. If anyone wants to beat me
to it please do.

**Comment by iainmerrick** [comment]
If you give me a rough idea of where to start, I can take a crack at it!

**Comment by pcj** [comment]
As workaround try redoing your BUILD files such that you're not globbing everything from the root of your project, i.e. create an `ink-engine-runtime/BUILD` and `inklecate/BUILD`.

**Comment by zaphar** [comment]
The script template is at 
https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/csharp.bzl#L128

The function that actually creates the run script is at:
https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/csharp.bzl#L128

That is where I would start investigating.

**Comment by iainmerrick** [comment]
Thanks! Just sent a pull request which should fix this.

As pcj suggested, I only hit this issue because my rules happened to be at the top level. Still seems worth fixing — working at the top level was the simplest way to compile this existing Xamarin project without modifying the code at all.

**Comment by iainmerrick** [comment]
Is anyone available to review my patch?

**Comment by iainmerrick** [comment]
Verified
