### ISSUE TITLE
Support for /nowarn

### ISSUE THREAD

**Issue by djungelorm** [bazelbuild/rules_dotnet#345]
`csharp_library` and its ilk accept attributes that control the warning level and whether warnings are reported as errors, but they do not let you pass the `/nowarn` flag to the compiler to completely silence a warning.

I propose adding an attribute like `ignore_warnings = ["CS1591"]` to the various rules, that gets turned into a `/nowarn:CS1591` flag for the compiler, and possibly a global setting for it as well just like the other warnings settings.

This would be useful to allow building with warning level 4, but certain warnings silenced (to avoid spam in bazel's console output).

**Comment by purkhusid** [comment]
I think it makes sense to add this flag to complete the warning settings.

**Comment by purkhusid** [comment]
This is now supported
