### ISSUE TITLE
Support RunAnalyzersDuringBuild=false

### ISSUE THREAD

**Issue by Place1** [bazelbuild/rules_dotnet#346]
Source code analysis can be very slow some large projects; and can effect build memory usage.

It'd be great if it was possible to disable analyzers: https://learn.microsoft.com/en-us/visualstudio/code-quality/disable-code-analysis?view=vs-2022

I'm guessing this would be possible in rules_dotnet by using a config flag to skip adding the `/analyzer` related flags to csc: https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/private/rules/csharp/actions/csharp_assembly.bzl#L366-L368

**Comment by purkhusid** [comment]
This sounds like an reasonable addition. I think this could be done in the same way as we do some of our other flags.
