### ISSUE TITLE
Support /unsafe compiler flag

### ISSUE THREAD

**Issue by fedemartinezdev** [bazelbuild/rules_dotnet#352]
I am trying to figure out how to set custom compiler flags for a `csharp_binary`. This is my first time using bazel in a project (actually porting an existing project just to learn) I would like to know if it is possible or if it needs to be implemented.

The error I am referring to is `error CS0227: Unsafe code may only appear if compiling with /unsafe`

**Comment by purkhusid** [comment]
This has to be added in the same manner as the other flags we currently support. Shouldn't be big task.

**Comment by fedemartinezdev** [comment]
I would like to contribute with it if you don't mind. Could you point me towards where this flag is and maybe where the others are to understand how it should be implemented?
