### ISSUE TITLE
Csharp_binary is able to compile but fails to find specific dependencies at runtime.

### ISSUE THREAD

**Issue by Mvk122** [bazelbuild/rules_dotnet#373]
I have a very large project that is compiling however it fails to find specific dependencies during runtime.
My setup is as follows:
1. All projects are in the same workspace.
2. Some projects depend on one another (though obviously there are no circular dependencies)
3. I then use publish_binary to create a non self-contained binary.
4. Since I don't want to use bazel run, I flatten out all the files so that there are a bunch of DLLs and runtime files in 1 folder by using `pkg_zip` from `"@rules_pkg//pkg:zip.bzl"`. I then unzip these to create the flattened folder. I'm aware that zipping just to unzip is a waste but this is the solution I have at the moment until we find a better solution.
5. Part of the included data is a Dockerfile which has an entrypoint which runs `dotnet ./OuterProject.dll`.
6. I then do docker build and docker run.

This all works and it runs for a second before reaching a part of the code where it fails to load the dependency with the following error:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Company.Common.Telemetry.Prometheus, Version=5.6.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Company.Common.Telemetry.Prometheus, Version=5.6.0.0, Culture=neutral, PublicKeyToken=null'
   at Company.Domain.Shared.Bootstrap.Default.TelemetryMetricsService.StartAsync(CancellationToken cancellationToken, IMetricServerCreator serverCreator)
```

`Company.Common.Telemetry.Prometheus` is included as one of the DLLs in that folder as `Company.Common.Telemetry.Prometheus.dll` and inspecting its properties it has file version `5.6.1.20783` which should be fine. This is meant to be a package dependency.

Is this setup not appropriate? How can this be fixed.

Additional details that might be relevant:

This is how the target's build file is:
```
load("@rules_dotnet//dotnet:defs.bzl", "csharp_binary", "publish_binary")
load("@rules_pkg//pkg:zip.bzl", "pkg_zip")
load("//bazel_funcs:vars.bzl", "var_providing_rule")
load("@bazel_skylib//rules:run_binary.bzl", "run_binary")

csharp_binary(
    name = "OuterTarget.Name",
    srcs = glob(
        ["**/*.cs"],
        exclude = ["obj/**/*"],
    ),
    allow_unsafe_blocks = True,
    data = [
        "Dockerfile",
        "appsettings.json",
        "healthcheck.sh",
        "entrypoint.sh",
    ],
    defines = ["BAZEL"],
    internals_visible_to = [],
    project_sdk = "web",
    target_frameworks = ["net6.0"],
    visibility = ["//visibility:public"],
    deps = [
        "//Path/To/File/TargetName",
        "@paket.company//Serilog:serilog",

    ],
)

publish_binary(
    name = "publish",
    binary = ":OurBinary.Name",
    self_contained = False,
    target_framework = "net6.0",
)

pkg_zip(
    name = "package",
    srcs = [
        ":publish",
    ],
    out = "package.zip",
)
```

An example of one of our project dependencies:
```
csharp_library(
    name = "Target.Name",
    srcs = glob(["**/*.cs"], exclude = ["obj/**/*"]),
    visibility = ["//visibility:public"],
    internals_visible_to = [],
    private_deps = [
        "@paket.company//Microsoft.NETCore.App.Ref:microsoft.netcore.app.ref",
        "//Other/Target",

    ],
    project_sdk = "default",
    target_frameworks = ["net6.0"],
    allow_unsafe_blocks = True,
    deps = [
        "@paket.company//Dependency",
    ],
    defines=["BAZEL"]
)
```

Note that other than for the outermost project, package dependencies are part of deps whereas project dependencies are in the private deps. This is because having project dependencies in the deps was making the analysis stage take up to an hour.

**Comment by purkhusid** [comment]
I'm not sure if it's going to be enough but don't use `private_deps` unless the dependency is not an runtime dependency.  The `private_deps` attribute is almost primarly used for targeting packs like the one you have ` "@paket.company//Microsoft.NETCore.App.Ref:microsoft.netcore.app.ref"`. 

Try moving all other dependencies to the `deps` attribute.

**Comment by Mvk122** [comment]
Thanks, is there any way to speed up the analysis cache? It has been stuck on the analysis phase for the past 45 minutes. The command I am running is `bazel build "//Path/to/Package/Target:package"   --loading_phase_threads=6 --jobs=6 --enable_runfiles -k`

**Comment by purkhusid** [comment]
Wow, how big of a project is this? I know there are some bottlenecks that @tomdegoede identified not too long ago. He has a large project as well but the analysis phase was not this slow.

What OS are you running?

**Comment by Mvk122** [comment]
I am running windows. The project has around 500k lines of code. There are 65 project references and in total, 492 packages in the paket.bzl file. 

Perhaps it is for some reason trying to analyse the bazel-bin and bazel-out folders for some reason? they are inline with the WORKSPACE.bazel file.

**Comment by purkhusid** [comment]
A couple of things:
I would make sure that you have folders that are not part of the build graph in `.bazelignore`, that includes folders that are ignored by `.gitignore`. I'm pretty sure that bazel should ignore the `bazel-*` automatically but you can try adding them as well to the `.bazelignore`.

Regarding the `deps`:
We have some documentation on this here: https://github.com/bazelbuild/rules_dotnet/tree/master/docs#design
The reason for having this the default is that it shrinks the input to actions significantly and makes the analysis phase smaller as well.

You can override this by adding `--@rules_dotnet//dotnet/settings:strict_deps=false` in your bazel invocation or in your `.bazelrc`. You can also override this on per target basis using: https://github.com/bazelbuild/rules_dotnet/blob/master/docs/csharp_binary.md#csharp_binary-override_strict_deps

**Comment by Mvk122** [comment]
I've added the bazel files to the .bazelignore as well as adding everything from my gitignore to it to no avail unfortunately. The analysis was left all night and didn't complete nor was there any commands on the terminal even with the ` --subcommands` option.

To aid in debugging, I compiled a much smaller part of the project. Here are the numbers:
* It has 34 project references
* This took `2647.602` seconds, i.e 45 minutes with a critical path of `14.80`s.
* 99.17% of this time was in the `Total interleaved loading-and-analysis phase time`
*  (2 packages loaded, 10077 targets configured), this is odd to me because the only target in any of the project references is the csharp_library rule itself.

I have uploaded the analysis here: https://github.com/Mvk122/Bazel-Out 

The command used was bazel build "//Path/To/File" --profile=myprofile.out   --loading_phase_threads=6 --jobs=6 --enable_runfiles -k  --subcommands.

Let me know if there is anything else I can try to reduce this analysis stage.

**Comment by purkhusid** [comment]
This is very unusual. I find it very likely that this is something specific with you setup. I've got a decently big .Net solution(150k lines of F# in around 350 targets) that I build with the current release and the analysis takes a couple of minutes but that is on Linux so it could be that Windows is causing some issues. Is it possible to build a part of the project on Linux to see if you have the same issues?

Can you share a bit more about your setup:
Any flags set in `bazelrc`?
Do you have `--windows_enable_symlinks` enabled?
Are you running in WSL or just normal Windows?
Are you using globs in `srcs`?

**Comment by Mvk122** [comment]
The project takes just as long to build on MacOS so I don't think this is something that Linux can help.  
This is the contents of my bazelrc:
```
startup --windows_enable_symlinks
build --enable_runfiles
```

Based on the bazelrc, `--windows_enable_symlinks` is enabled.

I am using normal windows.

Yes we are using globs. The globs are all `glob( ["**/*.cs"], exclude = ["obj/**/*"])`.

**Comment by purkhusid** [comment]
This is very unexpected. Can you do a `bazel query //some/target --output=build` on the targets and see if there are unexpected inputs in the attributes you use globs on? 

I'll take a look at some of our hot paths and see if I can clear some low hanging fruit.

**Comment by Mvk122** [comment]
Thanks! I have run the command you have just given on one of the projects that has 5 project dependencies and 7 package dependencies. I have some findings:

Here is the output given:
```
csharp_library(
  name = "Company.Something.MoreStuff",
  visibility = ["//visibility:public"],
  generator_function = "csharp_library",
  generator_location = "Path/To/Build/FIle/BUILD.bazel:6:15",
  deps = [The exact deps in the build file],
  target_frameworks = ["net6.0"],
  project_sdk = "default",
  runtime_identifier = select({"@rules_dotnet//dotnet/private:linux-x64": "linux-x64", "@rules_dotnet//dotnet/private:linux-arm64": "linux-arm64", "@rules_dotnet//dotnet/private:macos-x64": "osx-x64", "@rules_dotnet//dotnet/private:macos-arm64": "osx-arm64", "@rules_dotnet//dotnet/private:windows-x64": "win-x64", "@rules_dotnet//dotnet/private:windows-arm64": "win-arm64"}),
  internals_visible_to = [],
  private_deps = ["@paket.thetradedesk//Microsoft.NETCore.App.Ref:microsoft.netcore.app.ref"],
  treat_warnings_as_errors = False,
  override_treat_warnings_as_errors = False,
  warnings_as_errors = [],
  override_warnings_as_errors = False,
  override_warnings_not_as_errors = False,
  warning_level = 3,
  override_warning_level = False,
  strict_deps = True,
  override_strict_deps = False,
  srcs = [I've elaborated on this after the code block],
  allow_unsafe_blocks = True,
)
# Rule Company.Something.MoreStuff instantiated at (most recent call last):
#   C:/dev/path/Company.Something.MoreStuff/BUILD.bazel:6:15                      in <toplevel>
#   C:/users/my_name/_bazel_my_name/tj63ula4/external/rules_dotnet/dotnet/defs.bzl:106:20 in csharp_library
# Rule csharp_library defined at (most recent call last):
#   C:/users/my_name/_bazel_my_name/tj63ula4/external/rules_dotnet/dotnet/private/rules/csharp/library.bzl:52:22 in <toplevel>
```

Nothing looks suspicious. All the files in srcs are files from the top level project that is being built i.e 115 files. Some things I thought were interesting:

* The srcs only had the files of this "top level" library and not its project dependencies.
* I updated rules dotnet from 10.4 to 10.6 which invalidated the cache, when rebuilding it had a whopping (692 packages loaded, 6110 targets configured) which is definitely a lot larger than this subset of the project actually is.
* Building again after this gives (24 packages loaded, 178 targets configured).
* Building once more, everything is in the cache and I get  (0 packages loaded, 0 targets configured).
* When I try to compile one of its dependencies, it actually compiles instead of using something from the cache. This may be the source of our issue as a lot of our project dependencies are essentially ubiquitous. i.e they are referenced by almost every project. This lines up with paket dependencies essentially having no impact on increasing build times but project dependencies make analysis take forever.

I apologise for having to censor the files I paste here. This is a public forum afterall.

**Comment by purkhusid** [comment]
@Mvk122 Could you try this commit of rules_dotnet:
```
http_archive(
    name = "rules_dotnet",
    sha256 = "4d8c9cff37d0512ad9ade5a7253a4103507fdbaa6ac73464f5e7cc3f82a1ef3a",
    strip_prefix = "rules_dotnet-faef86e512239f89f37e557336b391411ab6d9f4",
    url = "https://github.com/bazelbuild/rules_dotnet/archive/faef86e512239f89f37e557336b391411ab6d9f4.tar.gz",
)
```
It's from this PR: https://github.com/bazelbuild/rules_dotnet/pull/377

**Comment by purkhusid** [comment]
Also, could you share:
paket.dependencies
paket.lock
The generated output from paket2bazel

**Comment by Mvk122** [comment]
Hi, the large project is still in its analysis phase while I write this message but there doesn't seem to be much improvement even in the small projects (projects that compile in 3 to 13 seconds). I have uploaded the files you have requested here: https://github.com/Mvk122/Bazel-Out

**Comment by purkhusid** [comment]
I do believe that the the rules are not handling your very deep dependency tree very well. I've noticed a couple of issues with how I'm collecting transitive runtime files and I've got a few ides on how to improve it. I'll get back to you once I've tried a  couple of things.

**Comment by purkhusid** [comment]
Could you try the latest commit on I have on the WIP branch:
```
http_archive(
    name = "rules_dotnet",
    sha256 = "5b641ad0f29684a506c652db5198783a2874adee75e73f5d347ec7b879b6e398",
    strip_prefix = "rules_dotnet-4849a046b80ab8aabf3647955fe16d73d4f99205",
    url = "https://github.com/bazelbuild/rules_dotnet/archive/4849a046b80ab8aabf3647955fe16d73d4f99205.tar.gz",
)
```

Also, did you disable strict deps? If you have them disabled, can you try with strict deps enabled?
If this is still slow, could you upload another profile with these flags in your bazelrc:
```
common --experimental_profile_include_target_label
common --experimental_profile_include_primary_output 
common --experimental_collect_load_average_in_profiler
common --experimental_collect_system_network_usage
common --experimental_collect_worker_data_in_profiler
common --experimental_profile_additional_tasks=phase
common --experimental_profile_additional_tasks=action
common --experimental_profile_additional_tasks=action_check
common --experimental_profile_additional_tasks=action_lock
common --experimental_profile_additional_tasks=action_release
common --experimental_profile_additional_tasks=action_update
common --experimental_profile_additional_tasks=action_complete
common --experimental_profile_additional_tasks=info
common --experimental_profile_additional_tasks=create_package
common --experimental_profile_additional_tasks=remote_execution
common --experimental_profile_additional_tasks=local_execution
common --experimental_profile_additional_tasks=scanner
common --experimental_profile_additional_tasks=local_parse
common --experimental_profile_additional_tasks=upload_time
common --experimental_profile_additional_tasks=remote_process_time
common --experimental_profile_additional_tasks=remote_queue
common --experimental_profile_additional_tasks=remote_setup
common --experimental_profile_additional_tasks=fetch
common --experimental_profile_additional_tasks=vfs_stat
common --experimental_profile_additional_tasks=vfs_dir
common --experimental_profile_additional_tasks=vfs_readlink
common --experimental_profile_additional_tasks=vfs_md5
common --experimental_profile_additional_tasks=vfs_xattr
common --experimental_profile_additional_tasks=vfs_delete
common --experimental_profile_additional_tasks=vfs_open
common --experimental_profile_additional_tasks=vfs_read
common --experimental_profile_additional_tasks=vfs_write
common --experimental_profile_additional_tasks=vfs_glob
common --experimental_profile_additional_tasks=vfs_vmfs_stat
common --experimental_profile_additional_tasks=vfs_vmfs_dir
common --experimental_profile_additional_tasks=vfs_vmfs_read
common --experimental_profile_additional_tasks=wait
common --experimental_profile_additional_tasks=thread_name
common --experimental_profile_additional_tasks=thread_sort_index
common --experimental_profile_additional_tasks=skyframe_eval
common --experimental_profile_additional_tasks=skyfunction
common --experimental_profile_additional_tasks=critical_path
common --experimental_profile_additional_tasks=critical_path_component
common --experimental_profile_additional_tasks=handle_gc_notification
common --experimental_profile_additional_tasks=action_counts
common --experimental_profile_additional_tasks=action_cache_counts
common --experimental_profile_additional_tasks=local_cpu_usage
common --experimental_profile_additional_tasks=system_cpu_usage
common --experimental_profile_additional_tasks=cpu_usage_estimation
common --experimental_profile_additional_tasks=local_memory_usage
common --experimental_profile_additional_tasks=system_memory_usage
common --experimental_profile_additional_tasks=memory_usage_estimation
common --experimental_profile_additional_tasks=system_network_up_usage
common --experimental_profile_additional_tasks=system_network_down_usage
common --experimental_profile_additional_tasks=workers_memory_usage
common --experimental_profile_additional_tasks=system_load_average
common --experimental_profile_additional_tasks=starlark_parser
common --experimental_profile_additional_tasks=starlark_user_fn
common --experimental_profile_additional_tasks=starlark_builtin_fn
common --experimental_profile_additional_tasks=starlark_user_compiled_fn
common --experimental_profile_additional_tasks=starlark_repository_fn
common --experimental_profile_additional_tasks=action_fs_staging
common --experimental_profile_additional_tasks=remote_cache_check
common --experimental_profile_additional_tasks=remote_download
common --experimental_profile_additional_tasks=remote_network
common --experimental_profile_additional_tasks=filesystem_traversal
common --experimental_profile_additional_tasks=worker_execution
common --experimental_profile_additional_tasks=worker_setup
common --experimental_profile_additional_tasks=worker_borrow
common --experimental_profile_additional_tasks=worker_working
common --experimental_profile_additional_tasks=worker_copying_outputs
common --experimental_profile_additional_tasks=credential_helper
common --experimental_profile_additional_tasks=pressure_stall_io
common --experimental_profile_additional_tasks=pressure_stall_memory
common --experimental_profile_additional_tasks=dynamic_lock
```
Some of these flags might not be available in Bazel 6 so you can either run it with the latest pre release(`7.0.0-pre.20230906.2`) or just remove the ones that Bazel 6 complains about

**Comment by Mvk122** [comment]
Hi, the fixes to build times for deps worked! Gone down from 45 minutes to 2 minutes where most of the time is spent compiling rather than in analysis.

That being said, the runtime error from the first post still persists. 

I had to remove some of the flags to continue using the same version of bazel (6.2.1) and the new profile is here https://github.com/Mvk122/Bazel-Out/blob/main/newprofile.out

**Comment by purkhusid** [comment]
Is there any way that you could create a reproduction of this? Doesn't need to be the exact same dependencies, but just the same error. 

But from the error it seems like the version of the package does not fit with the dll that is inside the package. A possible solution would be to publish the package with matching versions in the manifest and the package version itself.
