### ISSUE TITLE
Error during NuGet download when using v2 URL

### ISSUE THREAD

**Issue by Inirit** [bazelbuild/rules_dotnet#378]
When using a v2 URL as the source for a NuGet package, the download of that package will fail with the following pattern of error:
```
ERROR: An error occurred during the fetch of repository 'nuget.amazon.lambda.serialization.systemtextjson.v2.3.1':
   Traceback (most recent call last):
        File "<bazel_path>/oeeul5lt/external/rules_dotnet/dotnet/private/rules/nuget/nuget_archive.bzl", line 324, column 29, in _nuget_archive_impl
                ctx.download_and_extract(urls, type = "zip", integrity = ctx.attr.sha512, auth = auth)
Error in download_and_extract: java.io.IOException: Error downloading [https://www.nuget.org/api/v2/amazon.lambda.serialization.systemtextjson/2.3.1] to <bazel_path>/oeeul5lt/external/nuget.amazon.lambda.serialization.systemtextjson.v2.3.1/temp2275121979138268792/2.3.1.zip: GET returned 404 Not Found
```

Looking at nuget_archive.bzl, it seems to be a bug with the string formatting for the URL. The comment claims the URL should be of the form "{source}/package/{id}/{version}", yet the actual URL that gets created is of the form "{source}/{package_id}/{package_version}". Using the URL from the above example error, reformatting it to match the comment will result in a successful package download (https://www.nuget.org/api/v2/package/amazon.lambda.serialization.systemtextjson/2.3.1)

**Comment by purkhusid** [comment]
Fixed in 6da67eb1a7c03a1d99b3e8c36746dcc082b3ffb7 on master
