### ISSUE TITLE
Request for visibility of Bazel target "paket2bazel.exe" to be set to public

### ISSUE THREAD

**Issue by Inirit** [bazelbuild/rules_dotnet#380]
We would like to incorporate @rules_dotnet//tools/paket2bazel:paket2bazel.exe as a component in a custom rule for updating NuGet dependencies, however this is not possible because the target's visibility is private. Could this target be set to public?

Ultimately it would probably make sense for the custom rule I described to exist in rules_dotnet itself (in a similar manner as [compile_pip_requirements](https://github.com/bazelbuild/rules_python/blob/main/docs/pip.md#compile_pip_requirements)) rather than as a one-off implementation in a private repo, but for now this visibility change would be a quick way to unblock us.

**Comment by purkhusid** [comment]
Sure thing, I would also be interested in seeing the rule you are creating if you can share it! Already pushed the visibility change to master.

**Comment by Inirit** [comment]
> Sure thing, I would also be interested in seeing the rule you are creating if you can share it! Already pushed the visibility change to master.

I'd very much like to share it, perhaps even incorporating it with rules_dotnet if appropriate, but corporate legal shenanigans and near-term prioritization will disrupt that effort. It's something I will push for internally, though.
