### ISSUE TITLE
Option to remove default System imports.

### ISSUE THREAD

**Issue by Mvk122** [bazelbuild/rules_dotnet#384]
Some packages use different versions of common libraries that make it impossible to use them together in Bazel. I.e when using a library that uses System.Text.Json 7.0.0 in a net6.0 project we get:

```
FirstPackage\Program.cs(9,9): error CS0433: The type 'JsonSerializerOptions' exists in both 'System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
Target //SecondPackage:SecondPackage failed to build
```

A reproduction of the error and a possible solution is included in this repository: https://github.com/Mvk122/BazelBehaviourShowcase

**Comment by purkhusid** [comment]
This has been fixed in the latest release. There are some breaking changes, renamed `private_deps` to `targeting_packs` and you will need to regenerate the output of paket2bazel
