### ISSUE TITLE
Error While Building //examples/basic_csharp:hello Behind a Proxy

### ISSUE THREAD

**Issue by MattYoung50** [bazelbuild/rules_dotnet#392]
I'm pulling all of my dotnet_rules dependencies behind a web proxy in artifactory and I get the following issue when building the examples. Thoughts?

```txt
C:\Users\username\Documents\Build\rules_dotnet\examples>bazel --output_base=.bazel-build run //basic_csharp:hello --experimental_downloader_config=remote_downloader_config.txt
WARNING: Download from https://myproxyurl/github-%20platforms/platforms-0.0.7.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //basic_csharp:hello (46 packages loaded, 3352 targets configured).
INFO: Found 1 target...
ERROR: C:/users/username/documents/build/rules_dotnet/examples/basic_csharp/BUILD.bazel:9:14: Action basic_csharp/bazelout/net6.0/hello.exe failed: (Exit 1): apphost_shimmer.dll.bat failed: error executing command (from target //basic_csharp:hello) bazel-out\x64_windows-opt-exec-2B5CBBC6-ST-19c30ace4401\bin\external\rules_dotnet\dotnet\private\tools\apphost_shimmer\bazelout\net6.0\apphost_shimmer.dll.bat ... (remaining 3 arguments skipped)
ERROR: Manifest file C:\Users\username\Documents\Build\rules_dotnet\examples\.bazel-build\execroot\examples\bazel-out\x64_windows-opt-exec-2B5CBBC6-ST-19c30ace4401\bin\external\rules_dotnet\dotnet\private\tools\apphost_shimmer\bazelout\net6.0\apphost_shimmer.dll.bat.runfiles_manifest does not exist.
Target //basic_csharp:hello failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 39.770s, Critical Path: 7.49s
INFO: 16 processes: 12 internal, 4 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

bazel version: 6.3.2
OS: Windows 10 running build commands via Administrative Prompt in Powershell

**Comment by purkhusid** [comment]
I think your remote_downloader_config is not correctly configured. You are also trying to fetch bazel deps like the `platforms` package to your nuget proxy

**Comment by MattYoung50** [comment]
Is there a good way to tell which bazel deps are not getting proxied and pulled correctly? I've opened each of these `externel` deps and it seems they are populated and got pulled ok
![image](https://github.com/bazelbuild/rules_dotnet/assets/81185602/182b78e6-c2e3-4712-8765-bd04fbe60726)

**Comment by purkhusid** [comment]
I see that you are using Windows, do you have the following in your bazelrc?
```
startup --windows_enable_symlinks
build --enable_runfiles
```

**Comment by MattYoung50** [comment]
Yes. I've just cloned your repo and am using just building the examples/basic_csharp example and using the .bazelrc in examples.

**Comment by purkhusid** [comment]
Could you give me the following info:
Windows version
Bazel version

Also, I'm not sure if it's good to set `--output_base` to a directory inside the workspace. I would move it outside of the workspace.

**Comment by MattYoung50** [comment]
bazel version: 6.3.2
OS: Windows 10 running build commands via Administrative Prompt in Powershell

**Comment by MattYoung50** [comment]
That actually just fixed it @purkhusid! I moved my `--output_base` path outside of the local directory and into the parent directory and it compiled successfully! Thanks for the support. You can close this now.

**Comment by MattYoung50** [comment]
So this issue wasn't related to the proxy `--experimental_downloader_config` at all but instead was an issue with rules_dotnet not liking building to a directory within the workspace using the `--output_base` argument.
