### ISSUE TITLE
Question: how to toggle between release and debug mode?

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#396]
For example in an `fsharp_binary`

**Comment by purkhusid** [comment]
I have actually wanted to make this a bit nicer. Currently we use the Bazel way of switching between by using https://bazel.build/docs/user-manual#compilation-mode.

rules_dotnet defaults to optimized builds but if you set `--compilation_mode=dbg` org `-c dbg` it will use the debug flags

**Comment by purkhusid** [comment]
This is now documented here: https://github.com/bazelbuild/rules_dotnet/tree/master/docs#debugrelease-configurations
