### ISSUE TITLE
`targeting_packs`: attribute must be non empty.

### ISSUE THREAD

**Issue by criemen** [bazelbuild/rules_dotnet#410]
Hey,

per the docs in https://github.com/bazelbuild/rules_dotnet/blob/master/docs/csharp_library.md, the `targeting_packs` attribute is optional.

However, I'm getting an error message that it must be non-empty when (trying to) build a `csharp_library`.
I'm using 0.14.0.

**Comment by purkhusid** [comment]
This is a mistake in the docs, you need to provide the correct targeting packs for the target framework you choose. You can see how in the examples.

**Comment by criemen** [comment]
Thanks!

Yeah I expected that this is more of an error with the docs than the code, but I wanted to double-check.
