### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by paviln** [bazelbuild/rules_dotnet#411]
In the docs README https://github.com/bazelbuild/rules_dotnet/tree/master/docs: See the [paket2bazel](https://github.com/bazelbuild/rules_dotnet/blob/master/docs/tools/paket2bazel) docs for instructions on how to set Paket up with Bazel.

The paket2bazel does not exist? Or it does at https://github.com/bazelbuild/rules_dotnet/tree/master/tools/paket2bazel

**Comment by purkhusid** [comment]
Yeah, the link is pointing to the wrong location, should be https://github.com/bazelbuild/rules_dotnet/blob/master/tools/paket2bazel/README.md

You can also see how it's set up in the examples.

**Comment by purkhusid** [comment]
Link is fixed on master.
