### ISSUE TITLE
Simple aspnet8 app failed to build due to 'CS9137'

### ISSUE THREAD

**Issue by karataliu** [bazelbuild/rules_dotnet#414]
# Repro steps
1. Check out updated example with net8 from https://github.com/karataliu/rules_dotnet/tree/net8example/examples (or apply commit https://github.com/karataliu/rules_dotnet/commit/13dd4b6908dc58f8eec71784ed6da8abd6868bb3)
2. Run `bazel build //aspnetcore:aspnetcore`, it can pass
3. Simply add one line `app.MapGet("/test", () => "");` to `examples/aspnetcore/Program.cs` before `app.Run("http://localhost:8000");`.
4. Run  `bazel build //aspnetcore:aspnetcore`, it will fail with error:
```
error CS9137: The 'interceptors' experimental feature is not enabled in this namespace. Add '<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Microsoft.AspNetCore.Http.Generated</InterceptorsPreviewNamespaces>' to your project.
```

# Findings:

1. Ref to https://github.com/dotnet/roslyn/blob/main/docs/features/interceptors.md
Interceptors are an experimental compiler feature planned to ship in .NET 8 (with support for C# only). The feature may be subject to breaking changes or removal in a future release.

3. When looking at `bazel-out/**/bin/aspnetcore/aspnetcore/net8.0/aspnetcore.dll-0.params`, follow DLLs are added to analyzer:
```
/analyzer:external/nuget.microsoft.aspnetcore.app.ref.v8.0.1/analyzers/dotnet/cs/Microsoft.AspNetCore.Http.RequestDelegateGenerator.dll
/analyzer:external/nuget.microsoft.aspnetcore.app.ref.v8.0.1/analyzers/dotnet/cs/Microsoft.Extensions.Configuration.Binder.SourceGeneration.dll
/analyzer:external/nuget.microsoft.aspnetcore.app.ref.v8.0.1/analyzers/dotnet/roslyn4.4/cs/Microsoft.Extensions.Logging.Generators.dll
/analyzer:external/nuget.microsoft.aspnetcore.app.ref.v8.0.1/analyzers/dotnet/roslyn4.4/cs/Microsoft.Extensions.Options.SourceGeneration.dll
```

According to https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#package-a-generator-as-a-nuget-package
```
Solution: Generators can be packaged using the same method as an Analyzer would. Ensure the generator is placed in the analyzers\dotnet\cs folder of the package for it to be automatically added to the users project on install.
```

Those new generators are put in same location of analyazer, which are then loaded as analyzers in https://github.com/bazelbuild/rules_dotnet/blob/38bf1c6e69aac0a3a596b2236d0f7e82ed97e5ed/dotnet/private/rules/nuget/nuget_archive.bzl, that resulted the issue.

# Workaround
By skipping analyzers https://github.com/karataliu/rules_dotnet/commit/a7b554289943227c42d441372636c1c49d8304b1, the build will pass.

# Discussion
How to address the issue?
1. (long term) Detect analyzer and generators?
2. (short term) Provide an option to skip analyzers? #346

**Comment by purkhusid** [comment]
The analyzers support is kind of half baked at the moment. I also think that MSBuild must be adding some additional flag to the `csc` invocation when using .Net 8. I'm busy with other work/life things at the moment so I wont be able to take a look at this very soon. You could look at the compiler flags that MSBuild uses when building minimal C# APIs and I would be very open to an PR that fixes this.

**Comment by karataliu** [comment]
There doesn't seem to be a direct build flag on this. When comparing workable vs non-workable build, the only difference is this dll `Microsoft.AspNetCore.Http.RequestDelegateGenerator.dll` was (wrongly) added to analyzer, as it was indeed added to analyzers dir, but not a real analyzer.

I suppose a quick way to unblock is to provide an option to skip adding analyzers per #346.

**Comment by karataliu** [comment]
Added #419, verified it can solve the issue, could you please help a look?

**Comment by karataliu** [comment]
verified can work well after setting run_analyzers=False

**Comment by karataliu** [comment]
the fix is working well, is it possible to ship a new pre-release? That will enable building a basic aspnet8 app. Thanks.
