### ISSUE TITLE
When targetting framework version that differs from SDK version, runtimeconfig is generated with conflicting runtimeOptions

### ISSUE THREAD

**Issue by Inirit** [bazelbuild/rules_dotnet#422]
I recently attempted to update our dotnet SDK version from 6 to 8 while keeping our projects targeting net6.0. However, for binary targets this was creating runtimeconfig.json files that look like this:

```
{
	"runtimeOptions": {
		"frameworks": [
			{
				"name": "Microsoft.NETCore.App",
				"version": "8.0.0"
			}
		],
		"tfm": "net6.0"
	}
}
```
When attempting to run this on a machine that only has dotnet 6 available it fails to run. It's my expectation that if I build with a particular tfm then it ought to run against that version regardless of the SDK version that was used to build it. I **_think_** this runtimeconfig is the point of incompatibility.

**Comment by purkhusid** [comment]
This should be fixed on master. Will cut a release soon.
