### ISSUE TITLE
Recent commit broke our CI tests

### ISSUE THREAD

**Issue by vladmos** [bazelbuild/rules_dotnet#43]
The commit 30c1c31eff6a795b3e17ceb475439d326564ef19 broke our CI tests for both HEAD and latest versions of Bazel.

http://ci.bazel.io/job/rules_dotnet/

**Comment by pcj** [comment]
@zaphar I've been looking into this for a couple of days now.  I've been trying to imbue rules_dotnet with a travis-ci script that both executes and demonstrates that the latest commit is working....  so far  unable to demonstrate a functional outcome.  Seeing segmentation faults that are hard/slow to debug...

Perhaps the best thing is to [rollback #42](https://help.github.com/articles/reverting-a-pull-request/) until I can get this working on travis and be more confident that it's working more uniformly...

Other thoughts?

Sorry for any inconvenience.

**Comment by damienmg** [comment]
Travis might not have sandboxing enabled, which might be the issue (just a guess).

**Comment by zaphar** [comment]
I'll see if I can roll back later today.

**Comment by damienmg** [comment]
Do you want me to rollback the change?

**Comment by zaphar** [comment]
Yeah if you don't mind. My availability due to work has shrunk drastically
of late.

**Comment by damienmg** [comment]
Sure I'll do it
