### ISSUE TITLE
Incorrect publish folder layout for some RIDs

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#430]
The folder structure generated by `publish_binary` does not match `dotnet publish`. 
AFAICT, instead of using the supplied RID, it takes the resolved one. 

Here is the work-around:

```starlark
publish_binary(
  name = "app_alpine_x64",
  binary = ":app",
  target_framework = "net6.0",
  self_contained = True,
  runtime_identifier = "alpine-x64",
)

pkg_tar(
  name = "app_alpine_x64_archive",
  srcs = [
    ":app_alpine_x64",
  ],
  # strip_prefix = "app_alpine_x64/publish/linux-alpine-x64",
  strip_prefix = "app_alpine_x64/publish/linux-musl-x64",
  include_runfiles = True,
)
```

Full repro is here: https://github.com/njlr/rules-dotnet-publish-docker

The rule does not seem to take the user-defined `attr` into account? 
https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/private/rules/publish_binary/publish_binary.bzl#L175

**Comment by purkhusid** [comment]
This should now be fixed on master
