### ISSUE TITLE
Inconsistent appsettings.json handling during publish

### ISSUE THREAD

**Issue by mkempers** [bazelbuild/rules_dotnet#434]
When publishing a .NET application using MSBuild, the appsettings.json file is included in the root directory of the published output. However, this behavior is not observed when using the csharp_binary and publish_binary rules.

This inconsistency can be confusing for developers accustomed to MSBuild's behavior. It would be beneficial to understand the reasoning behind this difference and explore the possibility of including appsettings.json alongside the published binary by default (similar to MSBuild).

I am happy to contribute a solution if there's no specific technical limitation preventing this behavior.

**Comment by purkhusid** [comment]
How are you currently providing the appsettings.json? I don´t think I have any objections to adding `appsettings_file` to the rules that would be copied next to the executable.

**Comment by mkempers** [comment]
I add the ```appsetttings.json``` and ```appsetttings.development.json``` files as a data dependency like this:

```
csharp_binary(
    name = "service",
    out = "MyService",
    srcs = [
        "Program.cs",
    ],
    data = [
        "appsettings.json"
    ]+ glob(["appsettings.*.json"]),
    include_host_model_dll = True,
    project_sdk = "default",
    target_frameworks = ["net8.0"],
    deps = [
        "@rules_dotnet//tools/runfiles",
    ]
)
```
I use runfiles to load the appsettings files in my ```Program.cs```. This works during development, but when configuring the app during or after deployment you need to search for the settings file in the runfiles directory. Furthermore I don't like the build tooling dependency (runfiles) in my production code.
```
// Load appsettings from Bazel runfiles location
var runfiles = Runfiles.Create();
var appsettingsJsonFile = runfiles.Rlocation(
    "_main/my_service/appsettings.json"
);
var appsettingsEnvironmentJsonFile = runfiles.Rlocation(
    "_main/my_service/appsettings."
        + builder.Environment.EnvironmentName
        + ".json"
);
builder
    .Configuration.AddJsonFile(appsettingsJsonFile, false, true)
    .AddJsonFile(appsettingsEnvironmentJsonFile, true, true);
```
I already looked into adding ```appsettings_file```. I was wondering what provider to use for this. I was thinking ```DotnetAssemblyRuntimeInfo```.  Can I add it there?

**Comment by purkhusid** [comment]
Yeah, `DotnetAssemblyRuntimeInfo` makes sense. Since appsettings.json is a first class thing in .Net I think it makes sense to have it specific attribute in rules_dotnet as well.
