### ISSUE TITLE
bzlmod NuGet packages

### ISSUE THREAD

**Issue by josephrubin** [bazelbuild/rules_dotnet#439]
The docs for using NuGet packages are here (https://github.com/bazelbuild/rules_dotnet/blob/master/tools/paket2bazel/README.md)

They only discuss how to set this up with a WORKSPACE file. Is there any way to use NuGet packages with just a MODULE.bazel file?

**Comment by njlr** [comment]
This example may be helpful: https://github.com/njlr/rules-dotnet-publish-docker

**Comment by josephrubin** [comment]
Thank you, that is very helpful. Is there a reason that paket2bazel does not create an empty BUILD file in the output directory? As it stands, the generated files cannot be used

**Comment by njlr** [comment]
> Thank you, that is very helpful. Is there a reason that paket2bazel does not create an empty BUILD file in the output directory? As it stands, the generated files cannot be used

I suppose it's because the output directory is configurable, and there may already be a BUILD file in place?
