### ISSUE TITLE
Instructions for getting started is broken

### ISSUE THREAD

**Issue by jormundgand** [bazelbuild/rules_dotnet#53]
I've noticed the following issues with the instructions in the README.md to get started:

* The tag 0.0.3 doesn't exist -- using it makes bazel complain about it (as it should)
* Replacing tag 0.0.3 with the latest commit doesn't do anything; the result is that csharp_* rules are not recognized and cannot be used.
* Adding the nuget_package breaks the file.

If the nuget_package part is meant as an example, please move it to some other place and mark it as an example (a poor one at that); prefer using an example that the user can see working -- i.e. let it reference a real nuget package.

NB: I still haven't made this work and I'm currently relying on a custom genrule where I have a hardcoded path to csc compile on windows and rely on a system installed mcs on other platforms (hardly ideal).

**Comment by j3parker** [comment]
### Solutions for the things you mentioned
Issue #33 raised the problem with the 0.0.3 tag 2 years ago :(

To pull in what is currently master, use this in your workspace:

```python
http_archive(
    name = "io_bazel_rules_dotnet",
    url = "https://github.com/bazelbuild/rules_dotnet/archive/1a6ca96fe05bca83782464453ac4657fb8ed8379.zip",
    sha256 = "0f7d7f79bf543fdcce9ffebf422df2f858eae63367869b441d4d1005f279fa1f",
    strip_prefix = "rules_dotnet-1a6ca96fe05bca83782464453ac4657fb8ed8379",
)
```

Just guessing but you might have the wrong `strip_prefix`?

A "real" example of a `nuget_package` is:

```python
nuget_package(
  name = "Newtonsoft.Json",
  package = "Newtonsoft.Json",
  version = "10.0.3",
)
```

You can then use it by adding a `@Newtonsoft.Json//:dylibs` to your `deps`. This isn't a great design, you can read more about it in #18. In #27 an "escape hatch" was added so you can do whatever else you need but it's not exactly pretty. I have a closed source version that is a bit better I think but I haven't upstreamed it yet (PRs don't get merged very fast in this repo...)

### Bigger picture

I'll send some patches for the README in a little bit but I wouldn't hold my breath on them being merged fast.

I wouldn't really say this repo is currently maintained. I don't think that's the intent or a terminal thing, just that the Google employee that previously maintained it is really around anymore and it's not currently a focus for them.

If you're using Windows drop me a line at my work email, Jacob.Parker@D2L.com. We have a build with e.g. around 1500 `csharp_library` targets on Windows and are using a private fork of this repo. I'm trying to upstream the changes but it's a bit slow going.

On the topic of the path to the compiler, you may want to check out https://www.nuget.org/packages/Microsoft.Net.Compilers which will allow you to vendor the compiler (on Windows only; full xplat rules are going to be intricate.) I'm not aware of any solution to vendor the framework on Windows yet; we use the `dll_import` rule and create a new repository named `@NETFramework` to teach bazel about the framework (you import via e.g. `@NETFramework//:System.Linq`) This isn't yet ready for prime-time though.

**Comment by j3parker** [comment]
Ok I changed the `nuget_package` examples a bit. I didn't change the 0.0.3 release version though.

**Comment by jormundgand** [comment]
The one thing that really bothered me was the reference to the 0.0.3 tag -- people new to bazel (including myself) will be very frustrated by this not working. The nuget example isn't really necessary and having it in the "how to get started" doesn't help.

Bazel can be very hard to get into already, especially for someone like me who prefers plain old Make because of it's simplicity. Adding yet another part that's hard to use is really not a good thing.

**Comment by tomaszstrejczek** [comment]
The new implementation and documentation is now provided.
