### ISSUE TITLE
Windows/.NET Framework support

### ISSUE THREAD

**Issue by j3parker** [bazelbuild/rules_dotnet#54]
This is a tracking issue to document the work remaining to support Windows and .NET Framework in these rules.

High-priority:

- [ ] Cross-platform flags: #49
- [ ] [Toolchain](https://docs.bazel.build/versions/master/toolchains.html)ify the rules
- [ ] Vendor the compiler (likely via [Microsoft.Net.Compilers](https://www.nuget.org/packages/Microsoft.Net.Compilers))
- [ ] Improve the NuGet package import rules
   - Putting everything under a single `:dylibs` target falls apart pretty fast and may be a blocker if we depend on NuGet packages in the impl of these rules
   - It is also necessary if we support multiple .NET framework versions which is IMO essential in practice
- [ ] Allow the user to import their local .NET framework (since we probably can't vendor it ourselves.)
- [ ] Misc. additional flags (`/noconfig`, `/nostdlib` (I think), `/deterministic`, `/pathmap` ...)

Low-priority:

- [ ] Create a persistent-worker equivalent of VBCSCompiler.
   - This is very important for performance. I have a prototype. 
   - Official [blog post](https://blog.bazel.build/2015/12/10/java-workers.html)
   - Bazel [source](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/build/lib/worker)
   - A community [blog post](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/build/lib/worker)
   - Protocol: [worker_protocol.proto](https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/worker_protocol.proto)
  - A small shim reusing this code (probably pulled in via an `http_repository`) might be nice: https://github.com/dotnet/roslyn/tree/master/src/Compilers/Server/VBCSCompiler

**Comment by cdelguercio** [comment]
Does including references like System.Runtime.Serialization fall under this issue?

**Comment by j3parker** [comment]
Yes.

In our Windows fork we "import" the local .NET framework within our `WORKSPACE` and we reference a DLL like that with a label like `@NETFramework//:System.Runtime.Serialization` (this is prototype-level stuff though.)

It's worth spending some time figuring out how to best model this in Bazel (presumably with toolchains.) It's very common to target multiple versions of the .NET framework in a single project.

**Comment by tomaszstrejczek** [comment]
Yes, the new toolchains-based implementation supports windows and .NET.

**Comment by damienpontifex** [comment]
Is .NET Framework supported still? (e.g. net48)

Looking at https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/platform/list.bzl for supported frameworks it doesn't appear to be, but it could be specified elsewhere I've missed.

**Comment by damienpontifex** [comment]
Never mind, I can see they were dropped in https://github.com/bazelbuild/rules_dotnet/pull/208
