### ISSUE TITLE
Support for F#

### ISSUE THREAD

**Issue by samuela** [bazelbuild/rules_dotnet#69]
pretty please...

**Comment by samuela** [comment]
See also https://github.com/bazelbuild/bazel/issues/2864.

**Comment by njlr** [comment]
Are there any plans surrounding this?

**Comment by tomaszstrejczek** [comment]
Since I don't use nor know F# I do not plan to work on this issue.

**Comment by ezemtsov** [comment]
This is what stops us from using Bazel.
@tomaszstrejczek is it really hard to extend the current version to support F# dotnet core?

**Comment by purkhusid** [comment]
F# support has been merged into master: https://github.com/bazelbuild/rules_dotnet/pull/217

**Comment by njlr** [comment]
@purkhusid Thanks for this! 

In my own experiments, I found that the output of `dotnet` / `fsc` would contain the full-path to the source files. Do the Bazel rules strip this out? 

If so, would you mind sharing the flags that achieve this?

**Comment by purkhusid** [comment]
@njlr You can see all the compiler options used in this function: https://github.com/bazelbuild/rules_dotnet/blob/312dfb42f1e55dd7cbc5da0d1958de302b9643d1/dotnet/private/actions/assembly_core.bzl#L220

**Comment by ezemtsov** [comment]
@purkhusid thanks a lot for your effort!
@tomaszstrejczek do you think it's possible to make a stable release with F# support?

**Comment by tomaszstrejczek** [comment]
@ezemtsov Done
