### ISSUE TITLE
Set up Continuous Integration for PR verification

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/rules_dotnet#9]
We should set up CI to run for each pull request.

**Comment by damienmg** [comment]
We have CI, it's broken. See http://ci.bazel.io/job/rules_dotnet/ (even on the VM in which I installed mono).

I will work to add PR verification for all job on ci.bazel.io this quarter (among other things).

**Comment by davidzchen** [comment]
Got it. I mainly wanted to have it run for each PR and to add a badge to the README. Do you think it would be worth it to set up something on Travis similar to what is set up for [bazelbuild/rules_scala](https://travis-ci.org/bazelbuild/rules_scala) in the meantime?

**Comment by davidzchen** [comment]
Updated issue title for clarity.

**Comment by damienmg** [comment]
could make sense why not but I'd rather get it working on ci.bazel.io because we test for new release of Bazel AND we do test with sandboxing and non-batch mode.

**Comment by zaphar** [comment]
The bazel ci would make me feel better about submitted changes. How does one configure it? I'm looking at the ci site and not seeing anything obvious.

**Comment by damienmg** [comment]
This is resolved.
